### ISSUE TITLE
jsx-indent: crash

### ISSUE THREAD

**Issue by ljharb** [yannickcr/eslint-plugin-react#1015]
Using v6.9.0 - after upgrading from v6.3.0.

```jsx
function SFC() {
  return (
    <span>
      {true ?
        <div
        /> :
        <div
        />
      }
    </span>
  );
};
```

crashes with:
```sh
Cannot read property 'parent' of null
TypeError: Cannot read property 'parent' of null
    at EventEmitter.JSXOpeningElement ($PWD/node_modules/eslint-plugin-react/lib/rules/jsx-indent.js:238:27)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode ($PWD/node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode ($PWD/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode ($PWD/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter ($PWD/node_modules/eslint/lib/eslint.js:928:36)
    at Controller.__execute ($PWD/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse ($PWD/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse ($PWD/node_modules/eslint/lib/util/traverser.js:36:33)
```

**Comment by ljharb** [comment]
It seems like adding `prevToken &&` in the while condition [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-indent.js#L237) fixes it, but I'm not really sure why that's the case (other than that "a function that can return null is treated as if it never does")

**Comment by ljharb** [comment]
@yannickcr ping on this one

**Comment by ljharb** [comment]
This appears to already be fixed.
