### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by tcoopman** [yannickcr/eslint-plugin-react#109]
I get the following error with eslint-plugin-react:

**Atom Version**: 0.208.0
**System**: linux 4.0.5-1-ARCH
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.8

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of null

```
At /home/thomas/Workspace/ol-react/node_modules/eslint-plugin-react/lib/rules/prop-types.js:165

TypeError: Cannot read property 'type' of null
  at markPropTypesAsDeclared (/home/thomas/Workspace/ol-react/node_modules/eslint-plugin-react/lib/rules/prop-types.js:165:22)
  at EventEmitter.ClassProperty (/home/thomas/Workspace/ol-react/node_modules/eslint-plugin-react/lib/rules/prop-types.js:219:7)
  at emitOne (events.js:82:20)
  at EventEmitter.emit (events.js:166:7)
  at Controller.controller.traverse.enter (/home/thomas/Workspace/ol-react/node_modules/eslint/lib/eslint.js:725:25)
  at Controller.__execute (/home/thomas/Workspace/ol-react/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
  at Controller.traverse (/home/thomas/Workspace/ol-react/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
  at EventEmitter.module.exports.api.verify (/home/thomas/Workspace/ol-react/node_modules/eslint/lib/eslint.js:718:24)
  at /home/thomas/.atom/packages/linter-eslint/lib/linter-eslint.coffee:129:25
  at exports.allowUnsafeNewFunction (/home/thomas/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/home/thomas/.atom/packages/linter-eslint/lib/linter-eslint.coffee:128:7)
  at /home/thomas/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /home/thomas/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by yannickcr** [comment]
Can you post the code that trigger this error and what version of eslint-plugin-react is used ?

**Comment by tcoopman** [comment]
I've just updated everything today and I cannot reproduce it anymore.
