### ISSUE TITLE
wrap-multiline rule throws an error with the latest eslint

### ISSUE THREAD

**Issue by mbektimirov** [yannickcr/eslint-plugin-react#121]
Eslint v0.23.0
```
SublimeLinter: eslint output:
Cannot read property 'line' of undefined
TypeError: Cannot read property 'line' of undefined
    at isMultilines (/usr/local/lib/node_modules/eslint-plugin-react/lib/rules/wrap-multilines.js:33:26)
    at check (/usr/local/lib/node_modules/eslint-plugin-react/lib/rules/wrap-multilines.js:41:35)
    at EventEmitter.ReturnStatement (/usr/local/lib/node_modules/eslint-plugin-react/lib/rules/wrap-multilines.js:74:9)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:728:25)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:721:24)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:201:27)
    at CLIEngine.executeOnText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:361:26) 
```

**Comment by yannickcr** [comment]
Looks like #120.

> According to RReverser/acorn-jsx#24 Acorn introduced an API change between 1.0.3 and 1.2.2.
> 
> @RReverser unpublished acorn-jsx 1.1.0 from the npm registry (and bumped to 2.0.0), so if you re-install your dependencies acorn-jsx 1.0.3 will be used and everything should work again.
> 
> ```js
> $ rm -rf node_modules
> $ npm i
> ```
