### ISSUE TITLE
Exception in non-react code

### ISSUE THREAD

**Issue by okonet** [yannickcr/eslint-plugin-react#125]
Taking this code sample:

```
export default class TestClass {
    has
}
```

I'm getting an exception:

```
node_modules/eslint-plugin-react/lib/rules/prop-types.js:50
      if (tokens[0].value === 'propTypes' || tokens[1].value === 'propTypes') 
                                                      ^
TypeError: Cannot read property 'value' of undefined
    at isPropTypesDeclaration (node_modules/eslint-plugin-react/lib/rules/prop-types.js:50:55)
    at EventEmitter.ClassProperty (node_modules/eslint-plugin-react/lib/rules/prop-types.js:221:12)
    at EventEmitter.emit (events.js:107:17)
    at Controller.controller.traverse.enter (node_modules/eslint/lib/eslint.js:728:25)
    at Controller.__execute (node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (node_modules/eslint/lib/eslint.js:721:24)
    at processText (node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (node_modules/eslint/lib/cli-engine.js:226:12)
    at node_modules/eslint/lib/cli-engine.js:322:26

```

**Comment by yannickcr** [comment]
I added a check to avoid the plugin to crash.

But, is it really some valid code ? Babel accept it but output an empty Class, ignoring the `has` property.

**Comment by okonet** [comment]
Yes, the code is not valid, but the issue I had is that Intellij IDEA was showing a notification that ESLint had an error verifying my file, which IMO wasn't a case since I wasn't ready typing it.

**Comment by okonet** [comment]
And thanks for such a quick resolution! :sparkles: 

Will you publish a new version on npm soon?

**Comment by vith** [comment]
@yannickcr It's a problem for users running the linter in realtime. I get a popup about the uncaught TypeError in atom through linter-eslint as I'm typing a new class definition.

Related: https://github.com/AtomLinter/linter-eslint/issues/66

I can't reproduce anymore after switching to your master branch in my package.json:
```json
"eslint-plugin-react": "git://github.com/yannickcr/eslint-plugin-react.git#master",
```
So I think 228548f worked. Thanks. :+1:

**Comment by yannickcr** [comment]
> So I think 228548f worked. Thanks. :+1:

Happy to hear it :)

@okonet I will publish a new version this evening.
