### ISSUE TITLE
TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by roadhump** [yannickcr/eslint-plugin-react#129]
Got an error, probably some es7 case?

```
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at EventEmitter.ClassProperty (/Users/roadhump/Projects/Targetprocess/Mashups/ViewGallery/node_modules/eslint-plugin-react/lib/rules/jsx-sort-prop-types.js:64:53)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (/Users/roadhump/Projects/Targetprocess/Mashups/ViewGallery/node_modules/eslint/lib/eslint.js:728:25)
    at Controller.__execute (/Users/roadhump/Projects/Targetprocess/Mashups/ViewGallery/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/roadhump/Projects/Targetprocess/Mashups/ViewGallery/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/roadhump/Projects/Targetprocess/Mashups/ViewGallery/node_modules/eslint/lib/eslint.js:721:24)
    at processText (/Users/roadhump/Projects/Targetprocess/Mashups/ViewGallery/node_modules/eslint/lib/cli-engine.js:201:27)
    at CLIEngine.executeOnText (/Users/roadhump/Projects/Targetprocess/Mashups/ViewGallery/node_modules/eslint/lib/cli-engine.js:361:26)
    at Object.cli.execute (/Users/roadhump/Projects/Targetprocess/Mashups/ViewGallery/node_modules/eslint/lib/cli.js:179:70) 
```

`.babelrc` 

```
{
  "stage": 0
}
```

Code 
```js
var React, {Component, PropTypes} = require('react');
export default class HelpTooltipsManager extends Component {

    propTypes: {
        dispatch: PropTypes.func.isRequired,
        items: PropTypes.array.isRequired,
        visibility: PropTypes.object.isRequired
    }
}
```

**Comment by mathieumg** [comment]
Totally unrelated, by just out of curiosity, why do you not use the `import` syntax?

**Comment by yannickcr** [comment]
Seems your code is not valid, it should be `propTypes =` instead of `propTypes:`.

[In this case Babel do not trigger any error but it does not attach the propTypes method to the outputed class](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=var%20React%2C%20{Component%2C%20PropTypes}%20%3D%20require%28%27react%27%29%3B%0Aexport%20default%20class%20HelpTooltipsManager%20extends%20Component%20{%0A%0A%20%20%20%20propTypes%3A%20{%0A%20%20%20%20%20%20%20%20dispatch%3A%20PropTypes.func.isRequired%2C%0A%20%20%20%20%20%20%20%20items%3A%20PropTypes.array.isRequired%2C%0A%20%20%20%20%20%20%20%20visibility%3A%20PropTypes.object.isRequired%0A%20%20%20%20}%0A}).

However, I will patch the rule to avoid the crash but I will be difficult for us to validate the propTypes order since Babel does not output much informations here.

**Comment by roadhump** [comment]
@mathieumg I just rewrite my old code and some things are out of my attention, it will be import there.

**Comment by roadhump** [comment]
@yannickcr thanks. I thought that if code are not valid, babel will not parse it at all.

**Comment by yannickcr** [comment]
@roadhump yes, in it should not parse it, but there is a few cases were it accept invalid code (like in #125). I don't know if it can be considered as a bug or not.
