### ISSUE TITLE
Error when upgrading from 2.5.2 to 2.6.x

### ISSUE THREAD

**Issue by ericwooley** [yannickcr/eslint-plugin-react#137]
After upgrading I get this stacktrace.

```
(...)/node_modules/eslint-plugin-react/lib/rules/prop-types.js:421
        for (var k = 0, l = properties.length; k < l; k++) {
                                      ^
TypeError: Cannot read property 'length' of undefined
    at markPropTypesAsUsed ((...)/node_modules/eslint-plugin-react/lib/rules/prop-types.js:421:39)
    at EventEmitter.VariableDeclarator ((...)/node_modules/eslint-plugin-react/lib/rules/prop-types.js:549:7)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter ((...)/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:728:25)
    at Controller.__execute ((...)/node_modules/gulp-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse ((...)/node_modules/gulp-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify ((...)/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:721:24)
    at processText ((...)/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:201:27)
    at CLIEngine.executeOnText ((...)/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:361:26)
    at verify ((...)/node_modules/gulp-eslint/index.js:19:17)
    at Transform._transform ((...)/node_modules/gulp-eslint/index.js:37:18)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Transform.Writable.write (_stream_writable.js:217:11)
    at write ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform ((...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at (...)/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
    at evalmachine.<anonymous>:334:14
    at (...)/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:102:5
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
```

I am using these dependencies
```json
  "devDependencies": {
    "autoprefixer": "^5.2.0",
    "babel": "^5.6.5",
    "babel-eslint": "^3.1.17",
    "babelify": "^6.1.2",
    "browserify": "^10.2.4",
    "chai": "^3.0.0",
    "del": "^1.1.1",
    "envify": "^3.2.0",
    "es5-shim": "^4.1.7",
    "eslint-plugin-react": "^2.5.2",
    "gulp": "^3.9.0",
    "gulp-babel": "^5.1.0",
    "gulp-connect": "^2.2.0",
    "gulp-eslint": "^0.14.0",
    "gulp-if": "^1.2.5",
    "gulp-mocha-phantomjs": "^0.6.1",
    "gulp-notify": "^2.2.0",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-util": "^3.0.2",
    "gulp.spritesmith": "^3.7.0",
    "install": "^0.1.8",
    "mocha": "^2.2.5",
    "npm": "^2.11.3",
    "run-sequence": "^1.0.2",
    "scssify": "^0.3.3",
    "source-map-support": "^0.3.2",
    "uglifyify": "^3.0.1",
    "vinyl-buffer": "^1.0.0",
    "vinyl-paths": "^1.0.0",
    "vinyl-source-stream": "^1.0.0",
    "watchify": "^3.2.2"
  },
```

**Comment by yannickcr** [comment]
Sorry about that. Can you give me the source code that make it crash ?

**Comment by ericwooley** [comment]
Unfortunately it's a proprietary project, so I can't post the source. But Maybe I can narrow it down. Is there a way to turn on debug mode or something to that affect?

**Comment by jsg2021** [comment]
A file like this triggers it for me:
```
export default {
	componentWillMount () {
		let {foo} = this;
	}
};
```

**Comment by steida** [comment]
I have another isssue after update.

```
27:39  warning  'router.getCurrentQuery' is missing in props validation for Login  react/prop-types
28:22  warning  'router.replaceWith' is missing in props validation for Login      react/prop-types
```

2.5.2 works. File https://gist.github.com/steida/f2b2e9d6df01576c3fee

**Comment by mathieumg** [comment]
@steida You are using these props and they aren't in your `propTypes`.

**Comment by steida** [comment]
No, I'm using just two methods on prop router, and router is in propTypes.

**Comment by mathieumg** [comment]
My point, you didn't document `getCurrentQuery` and `replaceWith` under router.

**Comment by steida** [comment]
How I should do that?

**Comment by mathieumg** [comment]
```js
router:  React.PropTypes.shape({
  getCurrentQuery:  React.PropTypes.func,
  replaceWith:  React.PropTypes.func
})
```

Any of them can be appended with `.isRequired` too. See: https://facebook.github.io/react/docs/reusable-components.html#prop-validation

**Comment by steida** [comment]
Wow, I didn't know that. Thank you.

**Comment by steida** [comment]
Hmm, still somehow broken: Warning: Failed propType: Invalid prop `router` of type `function` supplied to `Login`, expected `object`.

**Comment by mathieumg** [comment]
That would be a React issue though, can I see what you are giving to the `router` prop?

**Comment by yannickcr** [comment]
@steida Can you create a separate issue for your specific problem ?

@jsg2021 @ericwooley this issue should be fixed in `v2.6.4`

**Comment by ryanflorence** [comment]
I'm getting this same error messages with this code:

```js
import React from 'react'

let debugContainer = document.createElement(debugContainer)
document.body.appendChild(debugContainer)

let styles = {
  position: 'fixed',
  top: 0,
  right: 0,
  width: 400,
  bottom: 0,
  background: '#444',
  color: '#f0f0f0',
  padding: 5,
  overflow: 'scroll',
}

export default function debug (Component) {
  let oldRender = Component.prototype.render

  Component.prototype.render = function () {
    let { state, props, context } = this
    let { name } = this.constructor
    setTimeout(() => {
      React.render(
        <pre style={styles}>
          {JSON.stringify({ name, state, props, context }, null, 2)}
        </pre>,
        debugContainer
      )
    }, 0)
    return oldRender.call(this)
  }

  return Component
}
```

Yes, this is the kind of code I write when nobody is looking > . >    < . <    > . >

**Comment by yannickcr** [comment]
Sorry but I cannot reproduce the crash with your code (eslint `v1.3.1`, eslint-plugin-react `v3.3.1`)
