### ISSUE TITLE
`boolean-prop-naming` triggers "Cannot read property 'properties' of undefined"

### ISSUE THREAD

**Issue by setek** [yannickcr/eslint-plugin-react#1452]
Hi,

I think this is similar to: https://github.com/yannickcr/eslint-plugin-react/issues/1369

I’m running 7.4.0 and still getting this error:

**package.json:**
`"eslint-plugin-react": "^7.4.0"`

`eslint` is 4.7.2

**.eslintrc.js:**
```
"react/boolean-prop-naming": [
    "error",
    { "rule": "^(is|has)[A-Z]([A-Za-z0-9]?)+" }
],
```

**Error:**
```
Cannot read property 'properties' of undefined
TypeError: Cannot read property 'properties' of undefined
    at EventEmitter.MemberExpression (/Users/user/repos/myrepo/node_modules/eslint-plugin-react/lib/rules/boolean-prop-naming.js:183:45)
    at emitOne (events.js:120:20)
    at EventEmitter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (/Users/user/repos/myrepo/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/user/repos/myrepo/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/Users/user/repos/myrepo/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/Users/user/repos/myrepo/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:606:23)
    at Traverser.enter (/Users/user/repos/myrepo/node_modules/eslint/lib/linter.js:962:32)
    at Traverser.__execute (/Users/user/repos/myrepo/node_modules/estraverse/estraverse.js:397:31)
    at Traverser.traverse (/Users/user/repos/myrepo/node_modules/estraverse/estraverse.js:501:28)
```

**The issue is stemming from this code:**
```
Card.propTypes = merge({}, Card.propTypes, {
    showScore: propTypes.bool
});
```

**Comment by louisscruz** [comment]
I'm getting the same issue. Can't implement this rule currently, but I'd very much like to. Any idea what the fix is?
