### ISSUE TITLE
jsx-no-bind: regression

### ISSUE THREAD

**Issue by Andarist** [yannickcr/eslint-plugin-react#1543]
I know this is not much, but I cannot dig into this deeper at the moment.
```
Module build failed: TypeError: Cannot read property 'type' of null
    at getNodeViolationType (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint-plugin-react/lib/rules/jsx-no-bind.js:72:28)
    at VariableDeclarator (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint-plugin-react/lib/rules/jsx-no-bind.js:139:39)
    at listeners.(anonymous function).forEach.listener (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>:null:null)
    at Object.emit (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/linter.js:959:32)
    at Traverser.__execute (/Users/mateuszburzynski/Desktop/chat-window/node_modules/estraverse/estraverse.js:397:31)
    at Traverser.traverse (/Users/mateuszburzynski/Desktop/chat-window/node_modules/estraverse/estraverse.js:501:28)
    at Traverser.traverse (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/util/traverser.js:31:22)
    at Linter._verifyWithoutProcessors (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/linter.js:956:19)
    at preprocess.map.textBlock (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/linter.js:997:35)
    at Array.map (<anonymous>:null:null)
    at Linter.verify (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/linter.js:996:42)
    at Linter.verifyAndFix (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/linter.js:1078:29)
    at processText (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/cli-engine.js:179:32)
    at CLIEngine.executeOnText (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint/lib/cli-engine.js:614:17)
    at lint (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/Users/mateuszburzynski/Desktop/chat-window/node_modules/eslint-loader/index.js:213:21)
```

**Comment by k1nger** [comment]
+1 just received the same error. Trying to look more into it right now.

**Comment by icd2k3** [comment]
Got this error after upgrading `eslint-plugin-react` from `7.4.0`-> `7.5.0`

**Comment by danrot** [comment]
Great! Thanks a lot 😃
