### ISSUE TITLE
Flow - defaultProp has no corresponding propTypes declaration react/default-props-match-prop-types

### ISSUE THREAD

**Issue by ionutcirja** [yannickcr/eslint-plugin-react#1554]
Hello, I'm using flow and and I'm getting this error.
I'm using the latest version: 7.5.1.
Here is the code.

```jsx
import type { FieldProps } from 'redux-form';

type Props = FieldProps & {
  name: string,
  type: string,
  label?: string,
  placeholder?: string,
  disabled?: boolean,
};

TextField.defaultProps = {
  label: '',
  placeholder: '',
  disabled: false,
};
```

**Comment by ardok** [comment]
This might be related, but I don't know.
At least this is what I'm seeing:

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
at properties.filter.property (/Users/ardo/Documents/workspace/zoltar/node_modules/eslint-plugin-react/lib/rules/default-props-match-prop-types.js:187:59)
at Array.filter (native)
at getPropTypesFromTypeAnnotation (/Users/ardo/Documents/workspace/zoltar/node_modules/eslint-plugin-react/lib/rules/default-props-match-prop-types.js:187:32)
at Object.handleStatelessComponent (/Users/ardo/Documents/workspace/zoltar/node_modules/eslint-plugin-react/lib/rules/default-props-match-prop-types.js:290:42)
at updatedRuleInstructions.(anonymous function) (/Users/ardo/Documents/workspace/zoltar/node_modules/eslint-plugin-react/lib/util/Components.js:654:75)
at listeners.(anonymous function).forEach.listener (/Users/ardo/Documents/workspace/zoltar/node_modules/eslint/lib/util/safe-emitter.js:47:58)
at Array.forEach (native)
at Object.emit (/Users/ardo/Documents/workspace/zoltar/node_modules/eslint/lib/util/safe-emitter.js:47:38)
at NodeEventGenerator.applySelector (/Users/ardo/Documents/workspace/zoltar/node_modules/eslint/lib/util/node-event-generator.js:251:26)
at NodeEventGenerator.applySelectors (/Users/ardo/Documents/workspace/zoltar/node_modules/eslint/lib/util/node-event-generator.js:280:22)
```

**Comment by ljharb** [comment]
@ardok your stack trace implies it's only a bug in `react/default-props-match-prop-types`

**Comment by ryami333** [comment]
Can reproduce too, my use-case also happens to be with a union type:
```jsx
// @flow

import React, { type ElementProps } from 'react';
import consecutive from 'consecutive';
import classnames from 'classnames';
import './radio.scss';

const next = consecutive();

export type RadioPropTypes = ElementProps<'button'> & {
    checked?: boolean,
    ...
};

function Radio(props: RadioPropTypes) {
    return (
        {/* ... */}
    );
}

Radio.defaultProps = {
    checked: false,
    ...
};

export default Radio;
```

Gives:
```bash
error  defaultProp "checked" has no corresponding propTypes declaration   react/default-props-match-prop-types
```

**Comment by dquang-tran** [comment]
This rule is no longer valid. If a prop has a default value, it no longer is optional.
https://github.com/facebook/flow/issues/1660

**Comment by ljharb** [comment]
It should still be valid for Flow v0.52 and below, regardless.
