### ISSUE TITLE
`no-access-state-in-setstate` throws on violations

### ISSUE THREAD

**Issue by elmigranto** [yannickcr/eslint-plugin-react#1559]
First of all, thank you everyone, who works on this project, it proved quite useful to me and I am really grateful! ❤️

Now, the problem is that `no-access-state-in-setstate` rule dies for me when violated. I have versions and stack, but not really sure if any other details are need, please let me know.

Thanks for your help. 

<hr/>

Versions:

```
eslint@4.11.0 
eslint-plugin-markdown@1.0.0-beta.7
eslint-plugin-react@7.5.1 
```

Stacktrace:

```
TypeError: Cannot read property 'name' of undefined
    at MemberExpression (<project-root>/node_modules/eslint-plugin-react/lib/rules/no-access-state-in-setstate.js:100:48)
    at listeners.(anonymous function).forEach.listener (<project-root>/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (<project-root>/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (<project-root>/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (<project-root>/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (<project-root>/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (<project-root>/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter (<project-root>/node_modules/eslint/lib/linter.js:959:32)
    at Traverser.__execute (<project-root>/node_modules/estraverse/estraverse.js:397:31)
```

**Comment by jomasti** [comment]
That link is a 404. Could you perhaps paste the source in the issue or produce another link if it is too long?

**Comment by elmigranto** [comment]
Sorry, didn't notice it was private repo. I removed everything that weren't triggering `TypeError`, here's what's left after:

```jsx
var SearchForm = createReactClass({
  render: function () {
    return (
      <div>
        {(function () {
          if (this.state.prompt) {
            return <div>{this.state.prompt}</div>
          }
        }).call(this)}
      </div>
    );
  }
});
```

Perhaps IIFE is the issue?

**Comment by ljharb** [comment]
wow, i'd never expect to see an IIFE ever again in a world with modules :-) interesting find!

**Comment by jay1337** [comment]
@yannickcr do you plan to release a new version soon with this fix ?

**Comment by saiichihashimoto** [comment]
I'm getting this issue in `7.6.0` but *not* `7.5.1`. :-)

**Comment by ljharb** [comment]
@saiichihashimoto could you file a new issue with the code that’s causing the crash, along with the stack trace?

**Comment by wmertens** [comment]
@saiichihashimoto maybe you got #1657?

**Comment by ljharb** [comment]
v7.6.1 is released; please file a new issue if there's still problems :-)
