### ISSUE TITLE
sort-prop-types autofix crash

### ISSUE THREAD

**Issue by moimael** [yannickcr/eslint-plugin-react#1582]
Hi,

I'm trying to get the autofix working on our codebase for the sort-prop-types rule but it crashes everytime i run it.

Here is the output I get from npm:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'lint', '--', '--fix' ]
2 info using npm@5.6.0
3 info using node@v8.9.1
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle galaxy@0.0.1~prelint: galaxy@0.0.1
6 info lifecycle galaxy@0.0.1~lint: galaxy@0.0.1
7 verbose lifecycle galaxy@0.0.1~lint: unsafe-perm in lifecycle true
8 verbose lifecycle galaxy@0.0.1~lint: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/mlavault/Development/galaxy/node_modules/.bin:/home/mlavault/.rbenv/shims:/home/mlavault/Android/Sdk/platform-tools/:/home/mlavault/android-studio/bin/:/home/mlavault/.rbenv/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/mlavault/.local/bin:/home/mlavault/bin:/usr/local/heroku/bin
9 verbose lifecycle galaxy@0.0.1~lint: CWD: /home/mlavault/Development/galaxy
10 silly lifecycle galaxy@0.0.1~lint: Args: [ '-c', 'eslint src "--fix"' ]
11 silly lifecycle galaxy@0.0.1~lint: Returned: code: 1  signal: null
12 info lifecycle galaxy@0.0.1~lint: Failed to exec lint script
13 verbose stack Error: galaxy@0.0.1 lint: `eslint src "--fix"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid galaxy@0.0.1
15 verbose cwd /home/mlavault/Development/galaxy
16 verbose Linux 4.13.16-300.fc27.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "lint" "--" "--fix"
18 verbose node v8.9.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error galaxy@0.0.1 lint: `eslint src "--fix"`
22 error Exit status 1
23 error Failed at the galaxy@0.0.1 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ljharb** [comment]
What if you run `./node_modules/.bin/eslint src --fix`?

**Comment by moimael** [comment]
It just shows me the eslint errors without doing any actual fixing

**Comment by moimael** [comment]
After checking the code for the rule, it seems that this particular rule do not implement autofix

**Comment by ljharb** [comment]
I’m confused then; i don’t see any crash, just the npm script exiting nonzero (presumably due to eslint errors).

Sorting is a tricky thing to autofix correctly, fwiw.
