### ISSUE TITLE
boolean-prop-naming triggers "Cannot read property 'properties' of undefined" 

### ISSUE THREAD

**Issue by np-8** [yannickcr/eslint-plugin-react#1594]
The problem is very similar to #1452 and #1354.

## System setup
Windows 10, node v.8.9.3, eslint-plugin-react v. 7.5.1, ESLint v.3.19.0

## Error
```
Cannot read property 'properties' of undefined
TypeError: Cannot read property 'properties' of undefined
    at EventEmitter.MemberExpression (C:\MyProject\node_modules\eslint-plugin-react\lib\rules\boolean-prop-naming.js:163:46)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at NodeEventGenerator.applySelector (C:\MyProject\node_modules\eslint\lib\util\node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (C:\MyProject\node_modules\eslint\lib\util\node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (C:\MyProject\node_modules\eslint\lib\util\node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (C:\MyProject\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (C:\MyProject\node_modules\eslint\lib\util\comment-event-generator.js:98:23)
    at Traverser.enter (C:\MyProject\node_modules\eslint\lib\eslint.js:929:36)
    at Traverser.__execute (C:\MyProject\node_modules\estraverse\estraverse.js:397:31)
```

### eslintrc.js
This happens with "any" rules given to `react/boolean-prop-naming`, for example: `"react/boolean-prop-naming": ["error", { "rule": "^is[A-Z]([A-Za-z0-9]?)+", "propTypeNames": ["bool"] }]`.
### file_to_be_linted.js
I was using copy-pasted [Icon component](https://github.com/gorangajic/react-icon-base/blob/master/index.js). The ~minimal code to reproduce the error is

```
import React from 'react'
import PropTypes from 'prop-types'

const IconBase = ({ width }, { reactIconBase = {} }) => {
  return (
    <h1>width</h1>
  )
}

IconBase.propTypes = {
  width: PropTypes.number
}

IconBase.contextTypes = {
  reactIconBase: PropTypes.shape(IconBase.propTypes)
}

export default IconBase
```
### Minimal changes to fix the error
Use a copy-pasted (not calculated) object literal inside the values in `contextTypes`. For example:

```
import React from 'react'
import PropTypes from 'prop-types'

const IconBase = ({ width }, { reactIconBase = {} }) => {
  return (
    <h1>width</h1>
  )
}

IconBase.propTypes = {
  width: PropTypes.number
}

IconBase.contextTypes = {
  reactIconBase: PropTypes.shape({
    width: PropTypes.number
  })
}

export default IconBase
```

**Comment by alexzherdev** [comment]
A safeguard against this was added in https://github.com/yannickcr/eslint-plugin-react/commit/56db72e56dd8cd17aa0bfd2861f5592ea2b3d60a#diff-65776338130f417c283ad71971cb90e9R164
https://github.com/yannickcr/eslint-plugin-react/blob/4e80833ffbfbe8bb8ae30301cd9dbaf6591666e4/lib/rules/boolean-prop-naming.js#L191-L193
