### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cinic** [yannickcr/eslint-plugin-react#1608]
Eslint -v: v4.13.1
Node -v: v6.12.0
Flow -v: 0.59.0
eslint-plugin-react v 7.5.1
babel-eslint 8.0.3

**Source code:**
```javascript
// @flow
import React, { PureComponent } from 'react';
import { connect } from 'react-redux';
import values from 'lodash/values';
import SelectInput from '../components/SelectInput/SelectInput';
import { setSummaryView } from '../actions/imms';
import { getI18nValues } from '../utils/app';
import type { AppState, Dispatch } from '../types/app';
import { SUMMARY_VIEWS } from '../constants/app';

type OwnProps = {
  value?: string,
  source?: Object[],
};
type DispatchProps = {
  onChange?: Function,
};
type Props = Props & DispatchProps;

const mapStateToProps = (state: AppState): OwnProps => ({
  value: state.imms.summaryView,
  source: getI18nValues(values(SUMMARY_VIEWS)),
});
const mapDispatchToProps = (dispatch: Dispatch): DispatchProps => ({
  onChange: summaryView => dispatch(setSummaryView(summaryView)),
});

@connect(mapStateToProps, mapDispatchToProps)
export default class GroupingModes extends PureComponent<Props> {
  render() {
    return <SelectInput {...this.props} />;
  };
}
```
**Raw Eslint output:**

```
RangeError: Maximum call stack size exceeded
    at propTypes.types.some.annotation (/home/cinic/projects/front/node_modules/eslint-plugin-react/lib/rules/prop-types.js:729:26)
    at Array.some (native)
    at declarePropTypesForIntersectionTypeAnnotation (/home/cinic/projects/front/node_modules/eslint-plugin-react/lib/rules/prop-types.js:724:30)
    at propTypes.types.some.annotation (/home/cinic/projects/front/node_modules/eslint-plugin-react/lib/rules/prop-types.js:734:18)
    at Array.some (native)
    at declarePropTypesForIntersectionTypeAnnotation (/home/cinic/projects/front/node_modules/eslint-plugin-react/lib/rules/prop-types.js:724:30)
    at propTypes.types.some.annotation (/home/cinic/projects/front/node_modules/eslint-plugin-react/lib/rules/prop-types.js:734:18)
    at Array.some (native)
    at declarePropTypesForIntersectionTypeAnnotation (/home/cinic/projects/front/node_modules/eslint-plugin-react/lib/rules/prop-types.js:724:30)
    at propTypes.types.some.annotation (/home/cinic/projects/front/node_modules/eslint-plugin-react/lib/rules/prop-types.js:734:18)
```

**Comment by cinic** [comment]
Omg, my fault. :man_facepalming: 
```javascript
type Props = Props & DispatchProps; 
```
No syntax errors — eslint exited with error code.

**Comment by ljharb** [comment]
This seems like something that the parser should error out on; this might need to be filed on babel-eslint.

**Comment by mickro** [comment]
just happened to me today:

"eslint": "^6.8.0",
"flow-bin": "^0.110.1"
"babel-eslint": "^10.1.0",
"eslint-plugin-react": "^7.19.0",

**Comment by ljharb** [comment]
@mickro try updating eslint-plugin-react and eslint?
