### ISSUE TITLE
react/prop-types: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by moretti** [yannickcr/eslint-plugin-react#163]
The following file:
```.js
import React, { PropTypes, Component } from 'react';

class Comp1 extends Component {
  render() {
    return <span />;
  }
}

Comp1.propTypes = {
  prop1: PropTypes.number.isRequired,
};

class Comp2 extends Component {
  render() {
    return <span />;
  }
}

Comp2.propTypes = {
  prop2: PropTypes.arrayOf(Comp1.propTypes.prop1).isRequired,
};
```

with eslint@0.24.1, eslint-plugin-react@2.7.1 and babel-eslint@3.1.23 produces the following error when `react/prop-types` is enabled:

```
TypeError: Cannot read property 'name' of undefined
    at markPropTypesAsDeclared (myApp/node_modules/eslint-plugin-react/lib/rules/prop-types.js:469:50)
    at EventEmitter.MemberExpression (myApp/node_modules/eslint-plugin-react/lib/rules/prop-types.js:548:11)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (myApp/node_modules/eslint/lib/eslint.js:724:25)
    at Controller.__execute (myApp/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (myApp/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (myApp/node_modules/eslint/lib/eslint.js:717:24)
    at processText (myApp/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (myApp/node_modules/eslint/lib/cli-engine.js:226:12)
    at myApp/node_modules/eslint/lib/cli-engine.js:322:26
```

**Comment by TamerShlash** [comment]
@moretti how were you able to bypass the issue?

**Comment by moretti** [comment]
I temporary disabled the rule by setting `"react/prop-types": 0` in `.eslintrc`

**Comment by yannickcr** [comment]
@TamerShlash Do you still have this issue even with the latest version ?

**Comment by TamerShlash** [comment]
@moretti @yannickcr thanks, I actually had a bug in my code, my fault :)

**Comment by yannickcr** [comment]
Oh ok, but the plugin should not crash even with incorrect code ;)

**Comment by TamerShlash** [comment]
@yannickcr when running:

    standard && webpack --config webpack.prod.js

It crashes with:

```
standard: Unexpected linter output:

TypeError: Cannot read property 'type' of undefined
    at markPropTypesAsDeclared (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:450:27)
    at /usr/local/lib/node_modules/standard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:572:9
    at Array.forEach (native)
    at EventEmitter.ObjectExpression (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:568:23)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/eslint.js:724:25)
    at Controller.__execute (/usr/local/lib/node_modules/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/eslint.js:717:24)
    at processText (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/cli-engine.js:201:27)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard
```

However, when running:

    npm run build

It gives proper error reporting:

```
> @0.0.0 build /Users/tamer/git/project/public
> standard && webpack --config webpack.prod.js

standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  /Users/tamer/git/project/public/app/components/pages/Users.jsx:188:10: Missing space before function parentheses.

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! @0.0.0 build: `standard && webpack --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @0.0.0 build script 'standard && webpack --config webpack.prod.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     standard && webpack --config webpack.prod.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tamer/git/project/public/npm-debug.log
```

I'm not sure which version that happened with, but since I didn't do any updates, it should be the same as the current which is `2.7.1`.

Sorry if that's not helpful, I'm still new to the modern JS world.

**Comment by yannickcr** [comment]
Actually the must helpful for me to find and fix the problem is
* the piece of code that makes the rule to crash
* the `.eslintrc` config file
* the `eslint` and `eslint-plugin-react` versions

**Comment by Nick-bcm** [comment]
**error:**
```
TypeError: Cannot read property 'type' of undefined
Occurred while linting /InputField.js:1
    at /node_modules/eslint-plugin-react/lib/rules/prop-types.js:153:39
    at Array.forEach (<anonymous>)
    at /eslint-plugin-react/lib/rules/prop-types.js:152:26
    at Array.forEach (<anonymous>)
    at isDeclaredInDestructuredParam (/node_modules/eslint-plugin-react/lib/rules/prop-types.js:147:14)
    at isDeclaredInComponent (/node_modules/eslint-plugin-react/lib/rules/prop-types.js:186:18)
    at /node_modules/eslint-plugin-react/lib/rules/prop-types.js:201:13
    at Array.filter (<anonymous>)
    at reportUndeclaredPropTypes (/node_modules/eslint-plugin-react/lib/rules/prop-types.js:198:51)
    at /node_modules/eslint-plugin-react/lib/rules/prop-types.js:223:11
```

**InputField.js**
```
import React from 'react'

const InputField = ({ input, meta: { touched, error }, cssClasses = {}, ...restProps }) => {
  restProps.className = cssClasses.base

  if (cssClasses.custom) {
    restProps.className += ` ${cssClasses.custom}`
  }
  if (touched && error) {
    restProps.className += ` ${cssClasses.error}`
  }

  return(
    <input
      {...input}
      {...restProps}
    />
  )
}

export default InputField
```

**.eslintrc.js**
```
module.exports = {
  env: {
    es6: true,
    node: true,
  },
  extends: ['airbnb'],
  parser: 'babel-eslint',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 12,
    sourceType: 'module',
  },
  plugins: ['react', 'import', 'jsx-a11y'],
  overrides: [
    {
      files: ['**/*.spec.js', '**/*.spec.jsx'],
      env: {
        jest: true,
      },
    },
  ],
  rules: {
    semi: ['error', 'never', { beforeStatementContinuationChars: 'always' }],
    'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
    // "react/prop-types": 0, // when uncomment - no error.
  },
}
```

**versions:**
```
    "eslint": "^7.9.0",
    "eslint-plugin-react": "^7.21.0",
```
