### ISSUE TITLE
no-unused-prop-types crashes when using a setState updater with no second param defined

### ISSUE THREAD

**Issue by gbedardsiceupgrade** [yannickcr/eslint-plugin-react#1685]
When using `setState` with an arrow function like so:

```
this.setState((prevState) => ({ count: prevState.count + 1 });
```

The plugin crashes with the following stack trace:

```
[Error - 11:49:56 AM] TypeError: Cannot read property 'properties' of undefined
    at markPropTypesAsUsed (/path/to/project/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:658:40)
    at handleSetStateUpdater (/path/to/project/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:955:7)
    at Object.handleFunctionLikeExpressions (/path/to/project/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:964:7)
    at updatedRuleInstructions.(anonymous function) (/path/to/project/node_modules/eslint-plugin-react/lib/util/Components.js:654:75)
    at listeners.(anonymous function).forEach.listener (/path/to/project/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/path/to/project/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/path/to/project/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/path/to/project/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/path/to/project/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/path/to/project/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter (/path/to/project/node_modules/eslint/lib/linter.js:959:32)
```

The plugin seems to assume that the second `props` param will be always defined on the function, when it actually won't always be the case.

**Comment by koba04** [comment]
@gbedardsiceupgrade Do you have an example code to reproduce this?

**Comment by ljharb** [comment]
I added a passing test linked to this issue; we’d definitely need a repro case.

@gbedardsiceupgrade can you try to reproduce this on v7.7.0?

**Comment by gbedardsiceupgrade** [comment]
Ah, looks like updating from `7.5.0` to `7.7.0` fixes it. Thanks for the awesome plugin! Closing.

**Comment by Leonard-Li777** [comment]
I updated to 7.10.0 still get the error!

prettier-eslint [ERROR]: eslint fix failed due to an eslint error
prettier-eslint-cli [ERROR]: There was an error formatting "/Users/lilun/workspace/supply-scm/src/layout/components/index.jsx":
    TypeError: Cannot read property 'properties' of undefined
        at markPropTypesAsUsed (/Users/lilun/workspace/supply-scm/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:670:41)
        at markDestructuredFunctionArgumentsAsUsed (/Users/lilun/workspace/supply-scm/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:953:9)
        at Object.handleFunctionLikeExpressions (/Users/lilun/workspace/supply-scm/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:982:7)
        at updatedRuleInstructions.(anonymous function) (/Users/lilun/workspace/supply-scm/node_modules/eslint-plugin-react/lib/util/Components.js:698:75)
        at listeners.(anonymous function).forEach.listener (/Users/lilun/workspace/supply-scm/node_modules/eslint/lib/util/safe-emitter.js:47:58)
        at Array.forEach (<anonymous>)
        at Object.emit (/Users/lilun/workspace/supply-scm/node_modules/eslint/lib/util/safe-emitter.js:47:38)
        at NodeEventGenerator.applySelector (/Users/lilun/workspace/supply-scm/node_modules/eslint/lib/util/node-event-generator.js:251:26)
        at NodeEventGenerator.applySelectors (/Users/lilun/workspace/supply-scm/node_modules/eslint/lib/util/node-event-generator.js:280:22)
        at NodeEventGenerator.enterNode (/Users/lilun/workspace/supply-scm/node_modules/eslint/lib/util/node-event-generator.js:294:14)
failure formatting 1 file with prettier-eslint
1 file was unchanged

**Comment by ljharb** [comment]
@Leonard-Li777 can you share the code it’s crashing on?

**Comment by ljharb** [comment]
Happy to fix it with a repro; please file a new issue.
