### ISSUE TITLE
Definition for rule 'react/jsx-max-props-per-line' was not found.

### ISSUE THREAD

**Issue by guocheng** [yannickcr/eslint-plugin-react#173]
Here is my .eslintrc

```json
{
    "env": {
      "node": true
    },
    "ecmaFeatures": {
        "jsx": true
    },
    "plugins":[
        "react"
    ],

    "rules": {
        "react/display-name": 1,
        "react/jsx-boolean-value": 1,
        "react/jsx-curly-spacing": 1,
        "react/jsx-max-props-per-line": 1,
        "react/jsx-no-duplicate-props": 1,
        "react/jsx-no-undef": 1,
        "react/jsx-quotes": 1,
        "react/jsx-sort-prop-types": 1,
        "react/jsx-sort-props": 1,
        "react/jsx-uses-react": 1,
        "react/jsx-uses-vars": 1,
        "react/no-danger": 1,
        "react/no-did-mount-set-state": 1,
        "react/no-did-update-set-state": 1,
        "react/no-multi-comp": 1,
        "react/no-unknown-property": 1,
        "react/prop-types": 1,
        "react/react-in-jsx-scope": 1,
        "react/require-extension": 1,
        "react/self-closing-comp": 1,
        "react/sort-comp": 1,
        "react/wrap-multilines": 1
      }
}
```

Here is the error output:

```
17:13 $ eslint components/AddButton.jsx
/Users/cheng/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/eslint.js:646
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'react/jsx-max-props-per-line' was not found.
    at /Users/cheng/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/eslint.js:646:27
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/cheng/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/eslint.js:619:16)
    at processText (/Users/cheng/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (/Users/cheng/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/cli-engine.js:226:12)
    at /Users/cheng/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/cli-engine.js:322:26
    at walk (/Users/cheng/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/util/traverse.js:81:9)
    at /Users/cheng/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/Users/cheng/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/util/traverse.js:101:11)
```

After removing this line, everything works again:

```
        "react/jsx-max-props-per-line": 1,
```

I am using eslint version **0.24.1**

**Comment by yannickcr** [comment]
The `jsx-max-props-per-line` rule is not published on npm yet, it should be added in next `eslint-plugin-react` release.

**Comment by guocheng** [comment]
Got it
