### ISSUE TITLE
Error in 7.8.0 Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by bdwain** [yannickcr/eslint-plugin-react#1785]
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at test (....node_modules/eslint-plugin-react/lib/util/version.js:30:25)
    at Object.testReactVersion (...node_modules/eslint-plugin-react/lib/util/version.js:39:10)

My eslint version is "4.19.1"
My node version is 9.11.1

**Comment by jsg2021** [comment]
Same with node 10.0.0 & eslint 4.19.1

**Comment by omarchehab98** [comment]
Same here

**Comment by omarchehab98** [comment]
Same with node version 7 & eslint 4.19.1

**Comment by ljharb** [comment]
Can anyone affected by this share their eslint config, and also more of the stack trace?

**Comment by ljharb** [comment]
@taddei I have a fix already, I just need a regression test.

**Comment by taddei** [comment]
ok cool, np.
feel free to discard this: https://github.com/yannickcr/eslint-plugin-react/pull/1786

**Comment by taddei** [comment]
the hotfix is just a patch though. I noticed that it's trying to see if the method `constructor` is deprecated, should probably skip core class methods like this one?

**Comment by ljharb** [comment]
aha, thanks, that did it :-)

**Comment by bdwain** [comment]
thanks for fixing this so quickly!

**Comment by fcastilloec** [comment]
I'm still seeing this error when using `eslint-plugin-react v7.8.2` with `eslint v4.19.1`, it supposed to have been fixed with `v7.8.1`. Here's the output I see:

```
[Error - 17:34:55] ESLint stack trace:
[Error - 17:34:55] TypeError: Cannot read property 'split' of undefined
    at test (.../node_modules/eslint-plugin-react/lib/util/version.js:30:24)
    at Object.testReactVersion (.../node_modules/eslint-plugin-react/lib/util/version.js:39:10)
    at isDeprecated (.../node_modules/eslint-plugin-react/lib/rules/no-deprecated.js:104:21)
    at checkDeprecation (.../node_modules/eslint-plugin-react/lib/rules/no-deprecated.js:109:12)
    at methods.forEach.method (.../node_modules/eslint-plugin-react/lib/rules/no-deprecated.js:162:35)
    at Array.forEach (native)
    at Object.checkLifeCycleMethods (.../node_modules/eslint-plugin-react/lib/rules/no-deprecated.js:162:17)
    at updatedRuleInstructions.(anonymous function) (.../node_modules/eslint-plugin-react/lib/util/Components.js:698:75)
    at listeners.(anonymous function).forEach.listener (.../node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
```

**Comment by jethrolarson** [comment]
I'm getting this one again with 
```
    "eslint": "5.11.1",
    "eslint-plugin-react": "7.12.1",
```

Setting this in .eslintrc.yaml is my work-around
    react/forbid-prop-types: 0

**Comment by jethrolarson** [comment]
done

**Comment by DylanVann** [comment]
This bug is in `7.12.3`. Issue should be re-opened.

**Comment by ljharb** [comment]
@dylanvann instead, a new issue should be filed - but luckily #2131 was filed and fixed already, and will be included in the next release.

**Comment by DylanVann** [comment]
@ljharb Awesome, and it has a test too 😄 . Thank you for letting me know
