### ISSUE TITLE
Regression: version check raises undefined error

### ISSUE THREAD

**Issue by LINKIWI** [yannickcr/eslint-plugin-react#1790]
Noticed a build failure here: https://travis-ci.org/LINKIWI/orion-web/builds/377922959

Seems to be related to the changeset from #1786; this is the only recent change affecting `lib/util/version.js`.

```
$ eslint .
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at test (/home/travis/build/LINKIWI/orion-web/node_modules/eslint-plugin-react/lib/util/version.js:30:25)
    at Object.testReactVersion (/home/travis/build/LINKIWI/orion-web/node_modules/eslint-plugin-react/lib/util/version.js:39:10)
    at isDeprecated (/home/travis/build/LINKIWI/orion-web/node_modules/eslint-plugin-react/lib/rules/no-deprecated.js:104:21)
    at checkDeprecation (/home/travis/build/LINKIWI/orion-web/node_modules/eslint-plugin-react/lib/rules/no-deprecated.js:109:12)
    at methods.forEach.method (/home/travis/build/LINKIWI/orion-web/node_modules/eslint-plugin-react/lib/rules/no-deprecated.js:162:35)
    at Array.forEach (<anonymous>)
    at Object.checkLifeCycleMethods (/home/travis/build/LINKIWI/orion-web/node_modules/eslint-plugin-react/lib/rules/no-deprecated.js:162:17)
    at updatedRuleInstructions.(anonymous function) (/home/travis/build/LINKIWI/orion-web/node_modules/eslint-plugin-react/lib/util/Components.js:698:75)
    at listeners.(anonymous function).forEach.listener (/home/travis/build/LINKIWI/orion-web/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
```

**Comment by ljharb** [comment]
That build ran with v7.8.0 (see the branch name), the PR you linked and the bugfix it contains is in v7.8.1.
