### ISSUE TITLE
no-unused-prop-types crashes when props type is intersection with union

### ISSUE THREAD

**Issue by thers** [yannickcr/eslint-plugin-react#1806]
A code like this:
```js
import * as React from 'react';

type OtherProps = {} | {};

type Props = OtherProps & {};

class Test extends React.PureComponent<Props> {}
```
will lead to:
```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at iterateProperties (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:364:22)
    at declarePropTypesForObjectTypeAnnotation (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:764:7)
    at propTypes.types.some.annotation (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:807:16)
    at Array.some (<anonymous>)
    at declarePropTypesForIntersectionTypeAnnotation (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:790:30)
    at markPropTypesAsDeclared (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:869:35)
    at Object.ClassDeclaration (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:992:11)
    at EventEmitter.updatedRuleInstructions.(anonymous function) (/node_modules/eslint-plugin-react/lib/util/Components.js:698:75)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
```
It's worth to mention that `type Props = ({} | {}) & {};` won't crash, but `type Props = (string) & {}` will fail with:
```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at propTypes.types.some.annotation (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:799:50)
    at Array.some (<anonymous>)
    at declarePropTypesForIntersectionTypeAnnotation (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:790:30)
    at markPropTypesAsDeclared (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:869:35)
    at Object.ClassDeclaration (/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:992:11)
    at updatedRuleInstructions.(anonymous function) (/node_modules/eslint-plugin-react/lib/util/Components.js:698:75)
    at listeners.(anonymous function).forEach.listener (/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/node_modules/eslint/lib/util/node-event-generator.js:251:26)
```

Plugin version is `7.9.1`.

**Comment by ljharb** [comment]
Probably unrelated, but import * as React is always incorrect - it’s only `import React from ‘react’`. Can you confirm you’re using flow? Usually only old and broken TypeScript docs ask for that incorrect syntax.

**Comment by thers** [comment]
Yes, I am using flow, and that is indeed unrelated as it crashes no matter if this line or not.
