### ISSUE TITLE
Error when upgrading to 7.11

### ISSUE THREAD

**Issue by bensampaio** [yannickcr/eslint-plugin-react#1943]
I upgraded to v7.11 and when I run eslint I get the following error:

```
TypeError: Cannot read property 'name' of undefined
    at markPropTypesAsDeclared (/path/node_modules/eslint-plugin-react/lib/util/propTypes.js:475:51)
    at Object.MemberExpression (/path/node_modules/eslint-plugin-react/lib/util/propTypes.js:644:9)
    at updatedRuleInstructions.(anonymous function) (/path/node_modules/eslint-plugin-react/lib/util/Components.js:706:43)
    at listeners.(anonymous function).forEach.listener (/path/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/path/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/path/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/path/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/path/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/path/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
```

Any idea what may cause this problem?

Besides that, I also get the following warning: `Warning: React version not specified in eslint-plugin-react settings.` In the README it says that there is a default. Besides that, why would I want to lock the react version in ESLint?

**Comment by alexzherdev** [comment]
Please upgrade to v7.11.1.
For the second question, see #1930.

**Comment by bensampaio** [comment]
Ok, I'll try that. Thanks!
