### ISSUE TITLE
[jsx-no-target-blank]TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by yoyo837** [yannickcr/eslint-plugin-react#1949]
```
<a href="">
  <Icon type="download" style={this.iconStyle} />
</a>
```
When I typed the end of the `target` word, it crashed.

```
<a href="" target>
  <Icon type="download" style={this.iconStyle} />
</a>
```

```
    "eslint": "^5.3.0",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-compat": "^2.5.1",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1",
```

```
[Error - 4:45:20 PM] ESLint stack trace:
[Error - 4:45:20 PM] TypeError: Cannot read property 'type' of null
    at isTargetBlank (/Users/tanghui/git/ydmap/ydmap-web-cloud/node_modules/eslint-plugin-react/lib/rules/jsx-no-target-blank.js:15:16)
    at JSXAttribute (/Users/tanghui/git/ydmap/ydmap-web-cloud/node_modules/eslint-plugin-react/lib/rules/jsx-no-target-blank.js:67:47)
    at listeners.(anonymous function).forEach.listener (/Users/tanghui/git/ydmap/ydmap-web-cloud/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/tanghui/git/ydmap/ydmap-web-cloud/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/tanghui/git/ydmap/ydmap-web-cloud/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/tanghui/git/ydmap/ydmap-web-cloud/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/tanghui/git/ydmap/ydmap-web-cloud/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/tanghui/git/ydmap/ydmap-web-cloud/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/Users/tanghui/git/ydmap/ydmap-web-cloud/node_modules/eslint/lib/linter.js:860:28)

```

**Comment by ljharb** [comment]
Altho a boolean is an invalid value for target, the rule shouldn’t be crashing.

**Comment by yoyo837** [comment]
Yes，I'm going to type the next  ‘=’ sign
