### ISSUE TITLE
Crash when using `for` loop iterator variable as prop value

### ISSUE THREAD

**Issue by dzek69** [yannickcr/eslint-plugin-react#2102]
This plugin crashes on this code (this is the simplest readable code, don't mind it's not very useful)

```
const Example = props => {
    for (let i = 0; i < length; i++) {
        return <Text key={i} />;
    }
};
```

```
TypeError: Cannot read property 'type' of null
    at isJSXElement (C:\Users\dzek\Projects\my-project\node_modules\eslint-plugin-react\lib\rules\jsx-max-depth.js:43:19)
    at find (C:\Users\dzek\Projects\my-project\node_modules\eslint-plugin-react\lib\rules\jsx-max-depth.js:93:20)
    at findJSXElement (C:\Users\dzek\Projects\my-project\node_modules\eslint-plugin-react\lib\rules\jsx-max-depth.js:104:49)
    at JSXExpressionContainer (C:\Users\dzek\Projects\my-project\node_modules\eslint-plugin-react\lib\rules\jsx-max-depth.js:139:25)
    at listeners.(anonymous function).forEach.listener (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\node-event-generator.js:294:14)
```

**Comment by ljharb** [comment]
Thanks for the great repro code; that helped a ton :-)

**Comment by dzek69** [comment]
I just realized that I could include my config. I'm glad it's fixed, thank you :)
