### ISSUE TITLE
Crash, when incrementing number in children used in props as well

### ISSUE THREAD

**Issue by dzek69** [yannickcr/eslint-plugin-react#2106]
version installed: 7.12.1

config: 
https://pastebin.com/Skm7Dgpn

```
let i = 1;
row.forEach(() => {
    return <Text key={i}>#{i++}</Text>
});
```

Eslint crashes on this code:
Removing the prop OR removing the children usage of `i` OR removing forEach OR replacing iteration with
```
let i = 1;
row.forEach(() => {
    i = i + 1;
    return <Text key={i}>{i}</Text>;
});
```
makes it work again

```
TypeError: Cannot read property 'type' of null
    at isJSXElement (C:\Users\dzek\Projects\my-project\node_modules\eslint-plugin-react\lib\rules\jsx-max-depth.js:43:19)
    at find (C:\Users\dzek\Projects\my-project\node_modules\eslint-plugin-react\lib\rules\jsx-max-depth.js:93:20)
    at findJSXElement (C:\Users\dzek\Projects\my-project\node_modules\eslint-plugin-react\lib\rules\jsx-max-depth.js:104:49)
    at JSXExpressionContainer (C:\Users\dzek\Projects\my-project\node_modules\eslint-plugin-react\lib\rules\jsx-max-depth.js:139:25)
    at listeners.(anonymous function).forEach.listener (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\Users\dzek\Projects\my-project\node_modules\eslint\lib\util\node-event-generator.js:294:14)
```

**Comment by ljharb** [comment]
The first code block there is not crashing for me on master.

**Comment by dzek69** [comment]
Looks like PHPStorm is caching something even after upgrade. When I run the same from command line it works just fine. Sorry for confusion.
