### ISSUE TITLE
[prefer-stateless-function] not work with @typescript-eslint/parser

### ISSUE THREAD

**Issue by clock157** [yannickcr/eslint-plugin-react#2187]
```bash
TypeError: Cannot read property 'body' of null
    at properties.some.property (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/rules/prefer-stateless-function.js:191:52)
    at Array.some (<anonymous>)
    at hasOtherProperties (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/rules/prefer-stateless-function.js:183:25)
    at Program:exit.Object.keys.forEach.component (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/rules/prefer-stateless-function.js:361:13)
    at Array.forEach (<anonymous>)
    at Object.Program:exit (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/rules/prefer-stateless-function.js:359:27)
    at updatedRuleInstructions.(anonymous function) (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint-plugin-react@7.12.4@eslint-plugin-react/lib/util/Components.js:756:75)
    at listeners.(anonymous function).forEach.listener (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint@5.15.0@eslint/lib/util/safe-emitter.js:52:26)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/puwei/Dev/code/ant-design-pro/node_modules/_eslint@5.15.0@eslint/lib/util/safe-emitter.js:49:38)
```

**Comment by ljharb** [comment]
Can you provide the code this is failing on?

**Comment by clock157** [comment]
hi, @ljharb. this is my code:
```ts
import * as React from 'react';
export interface IAvatarItemProps {
  tips: React.ReactNode;
  src: string;
  style?: React.CSSProperties;
}

export default class AvatarItem extends React.Component<IAvatarItemProps, any> {
  constructor(props: IAvatarItemProps);
}

```

**Comment by ljharb** [comment]
Thanks!

(as an aside; you'll want to enable esModuleInterop and synthetic imports; `import * as React` is never correct)

**Comment by clock157** [comment]
thanks for your correction @ljharb 👍

**Comment by golopot** [comment]
This bug happens because `constructor(props: IAvatarItemProps)` is missing function body (curly braces). In espree this is a parsing error, in ts-parser this parses successfully. Maybe it is a bug in ts-parser?

**Comment by ljharb** [comment]
It seems more likely that this plugin's rules just don't anticipate something that would never be valid in JS.
