### ISSUE TITLE
Warning: React version not specified in eslint-plugin-react settings.

### ISSUE THREAD

**Issue by posidron** [yannickcr/eslint-plugin-react#2252]
I noticed that this issue appeared already multiple times (in by-now closed bugs) in the past but it still seems to be present. Neither 'detect' nor providing an explicit version number seems to work for me.

```bash
$ rg "eslint-plugin-react" package.json 
114:    "eslint-plugin-react": "^7.12.4",
$ ./node_modules/.bin/eslint --version
v5.16.0
$ ./node_modules/.bin/prettier-eslint --version
4.7.1
$ ./node_modules/.bin/prettier-eslint --write 'src/**/*.{js,jsx}' --config=./prettier.config.js --prettier-ignore=.prettierignore
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
34 files were unchanged
```

**.eslintrc.js**
```javascript
[...]

module.exports = {
  parserOptions: {
    ecmaVersion: 2018,
    ecmaFeatures: {
      jsx: true
    }
  },
  env: {
    jest: true,
    node: true
  },
  parser: 'babel-eslint',
  extends: [
    'eslint:recommended',
    'plugin:flowtype/recommended',
    'plugin:react/recommended',
    'plugin:prettier/recommended',
    'prettier/flowtype',
    'prettier/react'
  ],
  plugins: ['flowtype', 'react', 'prettier', 'react-hooks'],
  settings: {
    flowtype: {
      onlyFilesWithFlowAnnotation: true
    },
    react: {
      pragma: 'React', // FWIW, I tried without as well.
      version: 'detect', // Tried with explicit version number as well.
      flowVersion: version('flow-bin')
    }
  },
  rules: {
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'warn'
  }
}
```

I added a `console.log(context.settings)` to node_modules/eslint-plugin-react/lib/util/version.js:41 but the object ist empty.

Am I not spotting something obvious or is it a bug?

**Comment by ljharb** [comment]
that looks like it should work to me. Do you get the same error if you invoke eslint directly?

**Comment by posidron** [comment]
Hm, I do not.

**Comment by ljharb** [comment]
That suggests that perhaps prettier-eslint is invoking eslint from the wrong directory, such that eslint-plugin-react can't locate the react version, or your eslintrc?

**Comment by posidron** [comment]
I provided now the `--eslint-path` parameter to the command and I am executing it from the project directory.

```bash
./node_modules/.bin/prettier-eslint \
  --config prettier.config.js \
  --ignore-path configs/prettier/prettierignore \
  --eslint-config-path configs/eslint/eslintrc.js \
  --eslint-path node_modules/.bin/eslint 'src/**/*.{js,jsx}'
```

```
Error: Cannot find module 'eslint-config-configs/eslint/eslintrc.js'
    at ModuleResolver.resolve (/Users/user/projects/foo/node_modules/prettier-eslint-cli/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/user/projects/foo/node_modules/prettier-eslint-cli/node_modules/eslint/lib/config/config-file.js:479:28)
    at Object.load (/Users/user/projects/foo/node_modules/prettier-eslint-cli/node_modules/eslint/lib/config/config-file.js:551:26)
    at formatFilesFromArgv (/Users/user/projects/foo/node_modules/prettier-eslint-cli/dist/format-files.js:193:63)
    at Object.<anonymous> (/Users/user/projects/foo/node_modules/prettier-eslint-cli/dist/index.js:36:27)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
```

Okay so all this is probably more of an issue with `prettier-eslint` rather than `eslint-plugin-react` I assume?
