### ISSUE TITLE
scope.block.parent is null, trying to reference scope.block.parent.key

### ISSUE THREAD

**Issue by theogravity** [yannickcr/eslint-plugin-react#231]
Using iojs@2.3.3, eslint-plugin-react@3.5.0, eslint@1.5.1, react@0.13.2. On OS X, the linter works fine. On our Ubuntu build system, it seems to fail:

```
[21:04:34][:npmInstall] > eslint . && rm -rf public/js && VAULT_CONFIG=prod NODE_ENV=production webpack
[21:04:34][:npmInstall] 
[21:04:56][:npmInstall] /mnt/work/teamcity/agent/work/3add2f360809ff9d/www/vault-server/node_modules/eslint-plugin-react/lib/util/component.js:45
[21:04:56][:npmInstall]     scope.block.parent.key && scope.block.parent.key.name === 'render'
[21:04:56][:npmInstall]                       ^
[21:04:56][:npmInstall] TypeError: Cannot read property 'key' of null
[21:04:56][:npmInstall]     at Object.isReactComponent (/mnt/work/teamcity/agent/work/3add2f360809ff9d/www/vault-server/node_modules/eslint-plugin-react/lib/util/component.js:45:23)
[21:04:56][:npmInstall]     at EventEmitter.ReturnStatement (/mnt/work/teamcity/agent/work/3add2f360809ff9d/www/vault-server/node_modules/eslint-plugin-react/lib/rules/no-multi-comp.js:42:26)
[21:04:56][:npmInstall]     at emitOne (events.js:82:20)
[21:04:56][:npmInstall]     at EventEmitter.emit (events.js:169:7)
[21:04:56][:npmInstall]     at NodeEventGenerator.enterNode (/mnt/work/teamcity/agent/work/3add2f360809ff9d/www/vault-server/node_modules/eslint/lib/util/node-event-generator.js:42:22)
[21:04:56][:npmInstall]     at CommentEventGenerator.enterNode (/mnt/work/teamcity/agent/work/3add2f360809ff9d/www/vault-server/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
[21:04:56][:npmInstall]     at Controller.controller.traverse.enter (/mnt/work/teamcity/agent/work/3add2f360809ff9d/www/vault-server/node_modules/eslint/lib/eslint.js:783:36)
[21:04:56][:npmInstall]     at Controller.__execute (/mnt/work/teamcity/agent/work/3add2f360809ff9d/www/vault-server/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
[21:04:56][:npmInstall]     at Controller.traverse (/mnt/work/teamcity/agent/work/3add2f360809ff9d/www/vault-server/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
[21:04:56][:npmInstall]     at EventEmitter.module.exports.api.verify (/mnt/work/teamcity/agent/work/3add2f360809ff9d/www/vault-server/node_modules/eslint/lib/eslint.js:780:24)
```

**Comment by theogravity** [comment]
We were missing `grunt-cli` in our package list and installed it, now works. Unsure how that would impact anything though since eslint isn't using grunt here. Just wanted to note how we fixed it on our end.

**Comment by yannickcr** [comment]
Very weird. I don't really see what's going on here, you should not have any difference between OSX/Ubuntu. Maybe you're linting your `node_modules` directory and the installed dependencies are not exactly the same ?

I'm closing this issue since the problem seems to be resolved for you. Feel free to reopen it if you encounter the same crash again.
