### ISSUE TITLE
Cannot read property 'type' of null on for...of destructuring

### ISSUE THREAD

**Issue by csvan** [yannickcr/eslint-plugin-react#2326]
Seeing this as of 7.14 (possibly 7.13, just recently updated from 7.12). The code itself has not changed the last month and has had consistent green builds until the version bump from 7.12.

Stack trace:

```
$ eslint --ext .js --ignore-path .gitignore src
TypeError: Cannot read property 'type' of null
Occurred while linting /Users/csvanefalk/IdeaProjects/ccsdk-scripts/src/scripts/webpack/index.js:40
    at Object.VariableDeclarator (/Users/csvanefalk/IdeaProjects/ccsdk-scripts/node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:464:21)
    at updatedRuleInstructions.(anonymous function) (/Users/csvanefalk/IdeaProjects/ccsdk-scripts/node_modules/eslint-plugin-react/lib/util/Components.js:780:47)
    at listeners.(anonymous function).forEach.listener (/Users/csvanefalk/IdeaProjects/ccsdk-scripts/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/csvanefalk/IdeaProjects/ccsdk-scripts/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/csvanefalk/IdeaProjects/ccsdk-scripts/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/csvanefalk/IdeaProjects/ccsdk-scripts/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/csvanefalk/IdeaProjects/ccsdk-scripts/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/csvanefalk/IdeaProjects/ccsdk-scripts/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/Users/csvanefalk/IdeaProjects/ccsdk-scripts/node_modules/eslint/lib/linter.js:752:32)
```

The offending code (file is proprietary so cannot share the full one): 

```
for (const { result, err } of results) {
    if (err) {
      return { error: true, errorText: err };
    }

    if (result.hasErrors()) {
      return {
        error: true,
        errorText: result.toString(),
      };
    }

    if (result.hasWarnings()) {
      warnings.push(
        result.toString({
          chunks: false,
          colors: true,
        }),
      );
    }
  }
```

**Comment by golopot** [comment]
Minimal reproducible code `for (const {a} of b) {}`, with `prop-types: 'error'`.
