### ISSUE TITLE
React as a `peerDependencies` package

### ISSUE THREAD

**Issue by fernandocamargo** [yannickcr/eslint-plugin-react#2332]
Hi folks! Thanks for the excellent work and very helpful plugin.

How to proceed when your module/package has `React` as a _peer dependency_?

```
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
Error: Error while loading rule 'react/no-deprecated': Cannot find module 'react' from '/Users/fernandocamargo/everything-dies/nodh'
Occurred while linting /Users/fernandocamargo/everything-dies/nodh/src/reducer/index.js
  at Function.module.exports [as sync] (/Users/fernandocamargo/everything-dies/nodh/node_modules/resolve/lib/sync.js:71:15)
  at detectReactVersion (/Users/fernandocamargo/everything-dies/nodh/node_modules/eslint-plugin-react/lib/util/version.js:19:31)
  at getReactVersionFromContext (/Users/fernandocamargo/everything-dies/nodh/node_modules/eslint-plugin-react/lib/util/version.js:39:25)
  at Object.testReactVersion (/Users/fernandocamargo/everything-dies/nodh/node_modules/eslint-plugin-react/lib/util/version.js:107:35)
  at usedPropTypesInstructions (/Users/fernandocamargo/everything-dies/nodh/node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:271:48)
  at Function.componentRule (/Users/fernandocamargo/everything-dies/nodh/node_modules/eslint-plugin-react/lib/util/Components.js:763:37)
  at createRuleListeners (/Users/fernandocamargo/everything-dies/nodh/node_modules/eslint/lib/linter/linter.js:697:21)
  at Object.keys.forEach.ruleId (/Users/fernandocamargo/everything-dies/nodh/node_modules/eslint/lib/linter/linter.js:865:31)
  at Array.forEach (<anonymous>)
  at runRules (/Users/fernandocamargo/everything-dies/nodh/node_modules/eslint/lib/linter/linter.js:810:34)
```

**.eslintrc**
```
{
  "root": true,
  "parser": "babel-eslint",
  "extends": [
    "airbnb",
    "prettier",
    "prettier/react"
  ],
  "plugins": [
    "import",
    "jest",
    "jsx-a11y",
    "prettier",
    "react",
    "react-hooks"
  ],
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "jest": true,
    "node": true
  },
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true,
    }
  },
  "settings": {
    "import/resolver": {
      "node": {
        "paths": ["src"]
      }
    },
    "react": {
      "version": "detect"
    }
  }
}
```

**package.json**
```
{
  "name": "@everything-dies/nodh",
  "version": "0.1.5",
  "main": "dist/index.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/everything-dies/nodh.git"
  },
  "author": "Fernando Camargo <camargodelbuono@gmail.com>",
  "license": "MIT",
  "private": false,
  "scripts": {
    "start": "babel ./src --watch --out-dir ./dist",
    "prepublishOnly": "babel ./src --out-dir ./dist -s inline"
  },
  "peerDependencies": {
    "react": "^16.8.6"
  },
  "dependencies": {
    "immutability-helper": "^3.0.1",
    "lodash": "^4.17.11",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-persist": "^5.10.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "babel-eslint": "^10.0.2",
    "babel-plugin-module-resolver": "^3.2.0",
    "eslint": "^6.0.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-jest": "^22.7.1",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "husky": "^2.5.0",
    "lint-staged": "^8.2.1",
    "prettier": "^1.18.2"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,jsx}": [
      "eslint"
    ],
    "src/**/*.{js,jsx,json,md}": [
      "prettier --list-different"
    ]
  }
}
```

**Comment by ljharb** [comment]
Every peer dep must also be a dep or a dev dep. if your package is published, you want peer + dev.

**Comment by fernandocamargo** [comment]
Thank you @ljharb! You're a hero.
