### ISSUE TITLE
react/prop-types - Empty destructuring of `this.props` causes crash

### ISSUE THREAD

**Issue by SpainTrain** [yannickcr/eslint-plugin-react#251]
If in a `render` function you have the line

```js
const {} = this.props;
```

and you run eslint with the `react/prop-types` enabled, eslint crashes with

```
TypeError: Cannot read property 'key' of undefined
    at getKeyValue (/home/spainhower/repos/homebuddy-webapp/node_modules/eslint-plugin-react/lib/rules/prop-types.js:186:19)
    at markPropTypesAsUsed (/home/spainhower/repos/homebuddy-webapp/node_modules/eslint-plugin-react/lib/rules/prop-types.js:366:11)
    at EventEmitter.MemberExpression (/home/spainhower/repos/homebuddy-webapp/node_modules/eslint-plugin-react/lib/rules/prop-types.js:547:11)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/home/spainhower/repos/homebuddy-webapp/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/home/spainhower/repos/homebuddy-webapp/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/home/spainhower/repos/homebuddy-webapp/node_modules/eslint/lib/eslint.js:782:36)
    at Controller.__execute (/home/spainhower/repos/homebuddy-webapp/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/spainhower/repos/homebuddy-webapp/node_modules/estraverse/estraverse.js:495:28)
```

**Comment by epmatsw** [comment]
Should be fixed by #234, but that hasn't made it into a release yet.
