### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by gmalcantara** [yannickcr/eslint-plugin-react#2519]
```jsx
const { RichEmbed, Util } = require("discord.js");
const YouTube = require("simple-youtube-api");
const ytdl = require("ytdl-core");
const { GOOGLE_KEY } = require("../../config.json");
//const { GOOGLE_KEY } = process.env;
const youtube = new YouTube(GOOGLE_KEY);
const choice = ["1⃣", "2⃣", "3⃣", "4⃣", "❌"];

module.exports.youtube = youtube;
module.exports.run = async (client, msg, args) => {
  try {
    if (args.length < 1) return args.missing(msg, "Nenhuma palavra chave, link ou lista de reprodução fornecida. \nPara saber como usar o comando, Use $ajuda play", this.help);
    const url = args[0] ? args[0].replace(/<(.+)>/g, "$1") : "";
    const voiceChannel = msg.member.voiceChannel;
    if (!voiceChannel) return msg.channel.send("🚫 Você deve se conectar num canal de voz primeiro.");
    //if (client.listenMOE.has(msg.guild.id)) return msg.channel.send("Woop im currently play listen.moe. maybe you can ~~wait~~ or stop it");
    if (client.queue.has(msg.guild.id) && voiceChannel.id !== client.queue.get(msg.guild.id).voiceChannel.id) return msg.channel.send(`Você deve se conectar em **${client.queue.get(msg.guild.id).voiceChannel.name}** para adicionar músicas na fila.`);
    const permissions = voiceChannel.permissionsFor(msg.client.user);
    if (!permissions.has("CONNECT")) return msg.channel.send("🚫 Eu não tenho permissão para **CONECTAR**.");
    if (!permissions.has("SPEAK")) return msg.channel.send("🚫 Eu não tenho permissão para **FALAR**.");
    if (url.match(/^https?:\/\/(www.youtube.com|youtube.com)\/playlist(.*)$/)) {
      const playlist = await youtube.getPlaylist(url);
      const videos = await playlist.getVideos();
      for (const video of Object.values(videos)) {
        const video2 = await youtube.getVideoByID(video.id);
        await this.handleVideo(client, video2, msg, voiceChannel, true);
      }
      return msg.channel.send(`✅ Playlist: **${playlist.title}** foi adicionado à fila!`);
    }
    try {
      const video = await youtube.getVideo(url);
      return this.handleVideo(client, video, msg, voiceChannel);
    } catch (e) {
      try {
        const videos = await youtube.searchVideos(args.join(" "), 4);
        let m = await msg.channel.send("Carregando...");
        for (const chot of choice) {
          await m.react(chot);
        }
        m = await embed(m, videos, "search");
        const filter = (rect, usr) => choice.includes(rect.emoji.name) && usr.id === msg.author.id;
        m.createReactionCollector(filter, { time: 60000, max: 1 })
          .on("collect", async col => {
            if (col.emoji.name === "❌") return m.delete();
            const oneUrl = await youtube.getVideoByID(videos[choice.indexOf(col.emoji.name)].id);
            return this.handleVideo(client, oneUrl, msg, voiceChannel);
          })
          .on("end", c => m.delete());
      } catch (err) {
        return msg.channel.send("🚫 Nenhum resultado encontrado");
      }
    }
  } catch (e) {
    return msg.channel.send(`Oh, não ocorreu um erro :( \`${e.message}\` tente mais tarde`);
  }
};

module.exports.handleVideo = async (client, video, msg, voiceChannel, playlist = false, force = false) => {
  const serverQueue = client.queue.get(msg.guild.id);
  const song = {
    id: video.id,
    title: Util.escapeMarkdown(video.title),
    thumbnail: video.thumbnails.high.url,
    url: `https://www.youtube.com/watch?v=${video.id}`,
    votes: [],
    duration: video.duration,
    requester: msg.author,
    loop: false
  };
  if (!serverQueue) {
    const queueConstruct = {
      textChannel: msg.channel,
      voiceChannel: voiceChannel,
      connection: null,
      songs: [],
      volume: 50,
      playing: true
    };
    client.queue.set(msg.guild.id, queueConstruct);
    queueConstruct.songs.push(song);
    try {
      const connection = await voiceChannel.join();
      queueConstruct.connection = connection;
      playlist ? undefined : embed(msg, song, "addQueue");
      play(client, msg.guild, queueConstruct.songs[0]);
    } catch (e) {
      client.queue.delete(msg.guild.id);
      return msg.channel.send(`Oh, não ocorreu um erro :( \`${e.message}\``);
    }
  } else {
    force ? serverQueue.songs.splice(1, 0, song) : serverQueue.songs.push(song);
    if (!playlist) return embed(msg, song, "addQueue");
  }
};

function play(client, guild, song, type = "biasa", seek = 0) {
  const serverQueue = client.queue.get(guild.id);
  if (!song) {
    serverQueue.voiceChannel.leave();
    return client.queue.delete(guild.id);
  }
  const dispatcher = serverQueue.connection.playStream(ytdl(song.url, { filter: "audioonly" }), { seek: seek })
    .on("end", res => {
      if (res !== "O fluxo não está gerando com rapidez suficiente.") console.error(res);
      if (res.includes("seek")) {
        const seekTo = parseInt(res.split(" ")[1], 10);
        serverQueue.songs.shift();
        play(client, guild, serverQueue.songs[0], "seek", seekTo);
      } else {
		 const shiffed = serverQueue.songs.shift();
        if (serverQueue.loop) serverQueue.songs.push(shiffed);
		 play(client, guild, serverQueue.songs[0]);
      }
    })
    .on("error", err => console.error(err));
  dispatcher.setVolume(serverQueue.volume / 50);
  type !== "seek" ? embed(serverQueue.textChannel, song) : undefined;
}
```

**ERROR:**

 if (res.includes("seek")) {
              ^
TypeError: Cannot read property 'includes' of undefined
at StreamDispatcher.serverQueue.connection.playStream.on.res (/app/src/commands/music/play.js:105:15)
    at StreamDispatcher.emit (events.js:189:13)
    at StreamDispatcher.destroy (/rbd/pnpm-volume/b43db2aa-52c2-4ecb-bf7d-870de6d34aa5/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:294:10)
    at AudioPlayer.destroyCurrentStream (/rbd/pnpm-volume/b43db2aa-52c2-4ecb-bf7d-870de6d34aa5/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/voice/player/AudioPlayer.js:77:18)
    at FfmpegProcess.transcoder.on.e (/rbd/pnpm-volume/b43db2aa-52c2-4ecb-bf7d-870de6d34aa5/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/voice/player/AudioPlayer.js:109:12)
    at FfmpegProcess.emit (events.js:194:15)
    at ChildProcess.process.on.e (/rbd/pnpm-volume/b43db2aa-52c2-4ecb-bf7d-870de6d34aa5/node_modules/.registry.npmjs.org/prism-media/0.0.3/node_modules/prism-media/src/transcoders/ffmpeg/FfmpegProcess.js:61:40)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)

**Comment by ljharb** [comment]
This doesn't seem like an issue with this eslint plugin.
