### ISSUE TITLE
`TypeError: Cannot read property 'match' of undefined` with `prefer-stateless-function`

### ISSUE THREAD

**Issue by garyking** [yannickcr/eslint-plugin-react#2596]
With the code:

```ts
/**
 * @param a.
 */
function Comp() {
  return <a></a>
}
```

Lint it with this rule, version `eslint-plugin-react@7.19.0`.

I get the error:

```
[Error - 11:18:15 PM] ESLint stack trace:
[Error - 11:18:15 PM] TypeError: Cannot read property 'match' of undefined
Occurred while linting test.tsx:4
    at scanIdentifier (eslint-plugin-react/node_modules/doctrine/lib/doctrine.js:259:96)
    at parseName (eslint-plugin-react/node_modules/doctrine/lib/doctrine.js:317:29)
    at TagParser.parseName (eslint-plugin-react/node_modules/doctrine/lib/doctrine.js:500:34)
    at TagParser.parse (eslint-plugin-react/node_modules/doctrine/lib/doctrine.js:769:34)
    at parseTag (eslint-plugin-react/node_modules/doctrine/lib/doctrine.js:790:26)
    at Object.parse (eslint-plugin-react/node_modules/doctrine/lib/doctrine.js:868:23)
    at Object.isExplicitComponent (eslint-plugin-react/lib/util/Components.js:269:35)
    at Object.isES6Component (eslint-plugin-react/lib/util/Components.js:237:17)
    at eslint-plugin-react/lib/rules/prefer-stateless-function.js:365:68
    at Array.forEach (<anonymous>)
```

This happens in particular, when I have ESLint linting while I type.

I managed to fix the issue in `doctrine` by adding `&& source[index]`, but then I find out that the package is archived on GitHub!

This bug might have been introduced recently (in the past week?), as I haven't seen it before.

**Comment by ljharb** [comment]
I doubt that, as eslint-plugin-react v7.19 has been out awhile.

Generally speaking, linting while typing isn't a supported use case, but it's nice to avoid crashes.

Given that doctrine is archived, it's unlikely we'll be able to fix this without removing our use of it - which also seems unlikely, but would be great to see via a PR.

**Comment by danavil87** [comment]
Is there any update to this? I just ran into the same issue and also got around it by adding the check
