### ISSUE TITLE
TypeError: sourceCode.isSpaceBetween is not a function

### ISSUE THREAD

**Issue by colinmcparland** [yannickcr/eslint-plugin-react#2611]
Weird this is happening only when running eslint, no warnings or errors show up while editing the file:

eslintrc:

```
module.exports = {
  extends: ["airbnb-typescript"],
  parserOptions: {
    project: './tsconfig.json'
  },
  rules: {
    "react/prop-types": 0,
    "@typescript-eslint/quotes": [
      "error",
      "double",
      {
        avoidEscape: true
      }
    ]
  },
  settings: {
    react: {
      version: "detect",
    }
  },
};

```

Error output
```
TypeError: sourceCode.isSpaceBetween is not a function
Occurred while linting somepath/src/charts/single-line/single-line.tsx:1
    at validateCommaSpacing (somepath/node_modules/@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js:87:44)
    at Program:exit.tokensAndComments.forEach (somepath/node_modules/@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js:131:21)
    at Array.forEach (<anonymous>)
    at Program:exit (somepath/node_modules/@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js:125:35)
    at listeners.(anonymous function).forEach.listener (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.leaveNode (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/node-event-generator.js:306:14)
```

package.json
```
...
"devDependencies": {
    "@commitlint/cli": "^7.2.1",
    "@commitlint/config-conventional": "^8.3.4",
    "@storybook/addon-a11y": "^5.0.0",
    "@storybook/addon-actions": "^5.0.0",
    "@storybook/addon-links": "^5.0.0",
    "@storybook/addon-notes": "^5.0.0",
    "@storybook/addon-options": "^5.0.0",
    "@storybook/addons": "^5.0.0",
    "@storybook/cli": "^5.0.0",
    "@storybook/react": "^5.0.0",
    "@testing-library/jest-dom": "^4.0.0",
    "@testing-library/react": "^8.0.6",
    "@types/jest": "^24.0.9",
    "@types/node": "^11.10.4",
    "@types/ramda": "^0.25.42",
    "@types/react": "^16.7.13",
    "@types/react-dom": "^16.0.11",
    "@types/react-helmet": "^5.0.7",
    "@types/react-intl": "^2.3.14",
    "@types/react-redux": "^7.0.1",
    "@types/react-router-dom": "^5.1.3",
    "@types/recharts": "^1.1.4",
    "@types/reduce-reducers": "^0.3.0",
    "@types/storybook__react": "^4.0.0",
    "@types/styled-components": "^4.1.3",
    "@typescript-eslint/eslint-plugin": "^2.24.0",
    "@typescript-eslint/eslint-plugin-tslint": "^2.25.0",
    "@typescript-eslint/parser": "^2.25.0",
    "ajv": "^6.6.1",
    "autoprefixer": "^9.4.2",
    "axios-mock-adapter": "^1.17.0",
    "babel-plugin-styled-components": "1.10.2",
    "boxen": "^3.0.0",
    "chalk": "^2.4.1",
    "commitizen": "^3.0.5",
    "cz-conventional-changelog": "^2.1.0",
    "docz": "^1.3.2",
    "docz-theme-default": "^1.2.0",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.7.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-typescript": "^7.2.0",
    "eslint-config-prettier": "^6.10.1",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.19.0",
    "eslint-plugin-react-hooks": "^2.5.0",
    "execa": "^1.0.0",
    "gamehubs-api-spec": "git+ssh://git@codehub.de.esl.systems:Frontend/gamehubs-api-spec.git#master",
    "husky": "^1.3.1",
    "hygen": "^4.0.9",
    "jest-enzyme": "^7.0.1",
    "jest-styled-components": "^6.3.1",
    "listr": "^0.14.3",
    "log-symbols": "^2.2.0",
    "mvy": "^0.1.0",
    "postcss-normalize": "^7.0.1",
    "react-app-rewire-postcss": "^3.0.2",
    "react-app-rewired": "^1.6.2",
    "react-router": "^5.1.0",
    "react-scripts": "2.1.0",
    "source-map-explorer": "^2.1.0",
    "storybook-react-router": "^1.0.2",
    "ts-jest": "^24.0.0",
    "ts-node": "8.4.0",
    "typescript": "^3.2.2",
    "xlsx": "^0.15.6"
  }
```

single-line.tsx
```
import React, { SFC, SVGProps } from "react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  ResponsiveContainer,
} from "recharts";
import { connect } from "react-redux";
import { ThemeInterface, styled } from "../../theme/util/helpers";
import {
  dividerColor,
  primaryAccentBackground,
} from "../../theme/theme/colors";
import { RootState } from "../../store/root";
import { themeSelector } from "../../theme/theme.selector";

export interface LineChartProps {
  theme: ThemeInterface;
  data: {
    xAxis: string | number;
    yAxis: string | number;
  }[];
  xAxis: string;
  yAxis: string;
}

const StyledChart = styled.div``;

interface AxisTickProps extends SVGProps<SVGElement> {
  payload: {
    coordinate: number;
    index: number;
    isShow: boolean;
    offset: number;
    tickCoord: number;
    value: string;
  };
}

const CustomizedAxisTick: SFC<AxisTickProps> = (props) => {
  const { x, y, payload } = props;

  return (
    <g transform={`translate(${x}, ${y})`}>
      <text
        x={0}
        y={0}
        dy={16}
        textAnchor="end"
        fill="currentColor"
        transform="rotate(-35)"
      >
        {payload.value}
      </text>
    </g>
  );
};

const Chart: SFC<LineChartProps> = (props) => {
  const { data, xAxis, yAxis } = props;
  const dividerColour = dividerColor(props);
  const backgroundColor = primaryAccentBackground(props);

  return (
    <StyledChart>
      <ResponsiveContainer width="99%" aspect={4 / 3}>
        <LineChart
          data={data}
          width={100}
          height={100}
          margin={{
            left: 10, top: 20, right: 50, bottom: 65,
          }}
        >
          <XAxis
            stroke="currentColor"
            dataKey="xAxis"
            name={xAxis}
            tickSize={10}
            axisLine={false}
            tickMargin={10}
            tick={CustomizedAxisTick}
            minTickGap={1}
          />

          <YAxis
            stroke="currentColor"
            dataKey="yAxis"
            name={yAxis}
            tickCount={10}
            axisLine={false}
            tickLine={false}
            tickMargin={10}
          />

          <CartesianGrid
            strokeDasharray="4 4"
            stroke={dividerColour}
            vertical={false}
          />

          <Line
            type="monotone"
            dataKey="yAxis"
            stroke={dividerColour}
            name={yAxis}
            strokeWidth={2}
            dot={{
              stroke: dividerColour,
              strokeWidth: 2,
              fill: backgroundColor,
              r: 3,
            }}
            isAnimationActive={false}
          />
        </LineChart>
      </ResponsiveContainer>
    </StyledChart>
  );
};

const mapStateToProps = (state: RootState) => ({
  theme: themeSelector(state),
});

export const SingleLineChart = connect(mapStateToProps)(Chart);

export { SingleLineChart as default };

```

**Comment by ljharb** [comment]
Does the airbnb-typescript package use the `@typescript-eslint/parser` parser?

**Comment by colinmcparland** [comment]
I believe they do, from the `package.json` from https://github.com/iamturns/eslint-config-airbnb-typescript:
```
"dependencies": {
    "@typescript-eslint/parser": "^2.24.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-config-airbnb-base": "^14.1.0"
  },
```

**Comment by ljharb** [comment]
Looks like the stack trace has the bug coming from one of typescript-eslint's rules, "comma-spacing" - why did you file an issue here?

**Comment by abhisek-niyo** [comment]
LInk to the issue reported issue https://github.com/typescript-eslint/typescript-eslint/issues/2031
