### ISSUE TITLE
`no-useless-fragment` fixer crash

### ISSUE THREAD

**Issue by SimenB** [yannickcr/eslint-plugin-react#2680]
Code:

```jsx
// comp.js
import React from 'react';

const Comp = () => (
  <html>
    <React.Fragment />
  </html>
);
```

Error:
```
TypeError: Cannot read property 'range' of null
Occurred while linting /Users/simen/repos/monorepo/comp.js:5
    at Object.fix (/Users/simen/repos/monorepo/node_modules/eslint-plugin-react/lib/rules/jsx-no-useless-fragment.js:175:94)
    at normalizeFixes (/Users/simen/repos/monorepo/node_modules/eslint/lib/linter/report-translator.js:178:28)
    at /Users/simen/repos/monorepo/node_modules/eslint/lib/linter/report-translator.js:343:49
    at Object.report (/Users/simen/repos/monorepo/node_modules/eslint/lib/linter/linter.js:905:41)
    at checkNode (/Users/simen/repos/monorepo/node_modules/eslint-plugin-react/lib/rules/jsx-no-useless-fragment.js:187:17)
    at JSXElement (/Users/simen/repos/monorepo/node_modules/eslint-plugin-react/lib/rules/jsx-no-useless-fragment.js:206:11)
    at /Users/simen/repos/monorepo/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/simen/repos/monorepo/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/simen/repos/monorepo/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
```

This is using `v7.20.1`

**Comment by ljharb** [comment]
Thanks for the repro; I'll have the fix released later today.

**Comment by ljharb** [comment]
v7.20.2 is released.
