### ISSUE TITLE
`forbid-prop-types` crashes on `PropTypes.shape`

### ISSUE THREAD

**Issue by MhMadHamster** [yannickcr/eslint-plugin-react#2682]
eslint: `v7.3.1`
eslint-plugin-react: `v7.20.1`

Code:
```javascript
import PropTypes from "prop-types";

const Foo = {
	foo: PropTypes.string,
};

const Bar = {
	bar: PropTypes.shape(Foo),
};
```
Error:
```
TypeError: Cannot read property 'forEach' of undefined
Occurred while linting C:\Projects\test\index.js:8
    at checkProperties (C:\Projects\test\node_modules\eslint-plugin-react\lib\rules\forbid-prop-types.js:91:20)
    at CallExpression (C:\Projects\test\node_modules\eslint-plugin-react\lib\rules\forbid-prop-types.js:173:11)
    at C:\Projects\test\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Projects\test\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Projects\test\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (C:\Projects\test\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (C:\Projects\test\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (C:\Projects\test\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:635:23)
    at C:\Projects\test\node_modules\eslint\lib\linter\linter.js:949:32
```

**Comment by Aerendir** [comment]
I have the same error.

**Comment by ljharb** [comment]
Thanks for the repro; I'll have the fix released later today.

**Comment by ljharb** [comment]
v7.20.2 is released.
