### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined makes eslint crash eslint-plugin-react\lib\rules\forbid-prop-types

### ISSUE THREAD

**Issue by MohammedYacub1029** [yannickcr/eslint-plugin-react#2691]
TypeError: Cannot read property 'forEach' of undefined
at checkProperties (reactworks\workspace\mui\node_modules\eslint-plugin-react\lib\rules\forbid-prop-types.js:91:20)
    at CallExpression (reactworks\workspace\mui\node_modules\eslint-plugin-react\lib\rules\forbid-prop-types.js:173:11)
    at reactworks\workspace\mui\node_modules\eslint\lib\util\safe-emitter.js:47:58
    at Array.forEach (<anonymous>)
    at Object.emit (reactworks\workspace\mui\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (reactworks\workspace\mui\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (reactworks\workspace\mui\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (reactworks\workspace\mui\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (reactworks\workspace\mui\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (reactworks\workspace\mui\node_modules\eslint\lib\linter.js:865:28)
    at Traverser._traverse (reactworks\workspace\mui\node_modules\eslint\lib\util\traverser.js:132:14)
    at Traverser._traverse (reactworks\workspace\mui\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (reactworks\workspace\mui\node_modules\eslint\lib\util\traverser.js:144:34)
    at Traverser._traverse (reactworks\workspace\mui\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (reactworks\workspace\mui\node_modules\eslint\lib\util\traverser.js:144:34)
    at Traverser._traverse (reactworks\workspace\mui\node_modules\eslint\lib\util\traverser.js:147:30)

when i change  "react/forbid-prop-types": [2, { "forbid": ["any"] }], to  "react/forbid-prop-types": [0, { "forbid": ["any"] }], in .eslintrc.json file error does not occur

versions:
Node: v12.14.0
react:16.13.1
eslint:4.19.1
eslint-react-plugin :7.20.2(which is published 15 hours ago)

**Comment by ljharb** [comment]
Do you know what code this is crashing on?

**Comment by ljharb** [comment]
Specifically, this was fixed in a9d2621f / #2682, which is included in v7.20.2. Are you sure that's the version you're using?

**Comment by ljharb** [comment]
v7.20.3 is released as well; so i'm going to close this, but will promptly reopen if you confirm this bug is still somehow happening (it should be impossible to call `forEach` on `undefined` in this codepath since v7.20.2)
