### ISSUE TITLE
react/forbid-prop-types crashes if a propType is a variable.

### ISSUE THREAD

**Issue by csilvers** [yannickcr/eslint-plugin-react#271]
This is using 3.6.3.

Here is my program:
```
var React = require("react");

var domainObjectPropType = React.PropTypes.any;

var NavMenuSection = React.createClass({
    propTypes: {
        domain: domainObjectPropType,
    },
});
```

Here is my eslintrc:
```
{
    "rules": {
        "react/forbid-prop-types": 1,
    },
    "env": {
        "es6": true,
    },
    "extends": "eslint:recommended",
    "plugins": [
        "react"
    ]
}
```

Here is my output:
```
% node_modules/.bin/eslint --config /var/tmp/eslintrc.short /var/tmp/bad.jsx
/home/csilvers/khan/devtools/khan-linter/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:71
      if (isForbidden(declaration.value.property.name)) {
                                                ^

TypeError: Cannot read property 'name' of undefined
    at /home/csilvers/khan/devtools/khan-linter/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:71:49
    at Array.forEach (native)
    at checkForbidden (/home/csilvers/khan/devtools/khan-linter/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:55:18)
    at /home/csilvers/khan/devtools/khan-linter/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:103:11
    at Array.forEach (native)
    at EventEmitter.ObjectExpression (/home/csilvers/khan/devtools/khan-linter/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:94:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/home/csilvers/khan/devtools/khan-linter/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/home/csilvers/khan/devtools/khan-linter/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
```

**Comment by csilvers** [comment]
(It may be difficult to resolve this in general, since who knows what value the var will have at runtime, but maybe a good solution would be to ignore such vars if they are actually `var` or `let`, but to examine their contents if they're `const`.  We are looking to change this code to use `const` anyway.)

**Comment by yannickcr** [comment]
Seems you are not using `3.6.3` but most likely `3.5.0` or `3.5.1`, the line reported does not exists anymore since #234. Upgrading to the last version should fix your problem.
