### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by sluukkonen** [yannickcr/eslint-plugin-react#2728]
Version 7.20.4 seems to crash with the following error in a non-tsx file.

```
yarn run v1.22.4
$ prettier packages/core/src/**/*.less --check && eslint packages --ext .js,.ts,.tsx --cache
Checking formatting...
All matched files use Prettier code style!

Oops! Something went wrong! :(

ESLint: 7.5.0

TypeError: Cannot read property 'name' of null
Occurred while linting /home/runner/work/exam-engine/exam-engine/packages/cli/src/commands/create-mex.ts:23
    at Object.getStatelessComponent (/home/runner/work/exam-engine/exam-engine/node_modules/eslint-plugin-react/lib/util/Components.js:692:45)
    at Object.getParentStatelessComponent (/home/runner/work/exam-engine/exam-engine/node_modules/eslint-plugin-react/lib/util/Components.js:728:42)
    at Object.getParentComponent (/home/runner/work/exam-engine/exam-engine/node_modules/eslint-plugin-react/lib/util/Components.js:623:18)
    at Object.ArrowFunctionExpression (/home/runner/work/exam-engine/exam-engine/node_modules/eslint-plugin-react/lib/util/Components.js:916:31)
    at updatedRuleInstructions.<computed> (/home/runner/work/exam-engine/exam-engine/node_modules/eslint-plugin-react/lib/util/Components.js:970:43)
    at /home/runner/work/exam-engine/exam-engine/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/exam-engine/exam-engine/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/exam-engine/exam-engine/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/exam-engine/exam-engine/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
```

I haven't been able to produce a reduced test case yet.

**Comment by xiekw2010** [comment]
+1

**Comment by PrimoZiv** [comment]
I have same problem.

`javascript
  // error:
  export default function () {}

  // success
  export default function name() {}
`

**Comment by bhovhannes** [comment]
Version 7.20.3 works fine.

**Comment by cy6erskunk** [comment]
Seems to be caused by https://github.com/yannickcr/eslint-plugin-react/pull/2696

**Comment by odinho** [comment]
Ah, I see someone reduced it already. An easy null-check on the `node.id.name` before it's used will fix this issue. Here's a full testcase:

```
odin@kaa:~/tmp/a$ cat default_export_without_name.js
export default function() {}
odin@kaa:~/tmp/a$ cat package.json 
{
  "scripts": {
    "test": "eslint default_export_without_name.js"
  },
  "dependencies": {
    "eslint": "^7.5.0",
    "eslint-plugin-react": "^7.20.4"
  }
}
odin@kaa:~/tmp/a$ cat .eslintrc 
{
    "env": { "es6": true },
    "plugins": ["react"],
    "parserOptions": { "sourceType": "module" },
    "extends": [ "plugin:react/recommended" ],
    "settings": { "react": { "version": "latest" } } 
}
```

**Comment by Roxyhuang** [comment]
today ,I have same problem. +1

**Comment by dukemai** [comment]
same problem here

**Comment by pevans01** [comment]
Same problem :-)

**Comment by odinho** [comment]
Instead of commenting, just click the :+1: on the top issue instead. Better for everyone ^_^

You may also help out with the PR at #2730 if it turns out anything is needed. Though currently just waiting on review from @ljharb. :)

**Comment by ljharb** [comment]
Thanks everyone; I'll try to get a fix out tonight.

**Comment by edokeh** [comment]
+1

And version 7.20.3 works
