### ISSUE TITLE
TypeError: Converting circular structure to JSON 7.20.4

### ISSUE THREAD

**Issue by glenngijsberts** [yannickcr/eslint-plugin-react#2729]
When running my lint command in CircleCI I get the following error:

```
PASS   lint  server/middlewares/inject-next.js
internal/child_process.js:778
    const string = JSON.stringify(message) + '\n';
                        ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Node'
    |     property 'left' -> object with constructor 'Node'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:778:25)
    at process.target.send (internal/child_process.js:676:19)
    at reportError (/root/code/node_modules/create-jest-runner/node_modules/jest-worker/build/workers/processChild.js:87:11)
    at reportClientError (/root/code/node_modules/create-jest-runner/node_modules/jest-worker/build/workers/processChild.js:71:10)
    at execFunction (/root/code/node_modules/create-jest-runner/node_modules/jest-worker/build/workers/processChild.js:142:5)
    at execHelper (/root/code/node_modules/create-jest-runner/node_modules/jest-worker/build/workers/processChild.js:124:5)
    at execMethod (/root/code/node_modules/create-jest-runner/node_modules/jest-worker/build/workers/processChild.js:128:5)
    at process.messageListener (/root/code/node_modules/create-jest-runner/node_modules/jest-worker/build/workers/processChild.js:46:7)
    at process.emit (events.js:210:5)
internal/child_process.js:778
    const string = JSON.stringify(message) + '\n';
```

It only occurs in my PR's that are using version `7.20.4`, PR's using version `7.20.3` are passing. It's running on yarn version `1.21.1` and on node version `v12.14.0`. I'm not sure if this is enough info since I'm not sure what to provide but I can provide more info if needed :)

**Comment by ljharb** [comment]
What would really help is the code that it's failing to lint, an error stack trace using `eslint` on the command line (as opposed to a jest runner), and which eslint parser you're using. Thanks!

**Comment by glenngijsberts** [comment]
@ljharb hey man, totally forgot about this issue. It seems that version `7.20.5` fixed this! Thanks for replying anyway :)
