### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by wereHamster** [yannickcr/eslint-plugin-react#2840]
```
export default class extends React.PureComponent<{}> {
  render() {
    return <div />
  }
}
```

The error is thrown in getDetectedComponents(), specifically line `return val.node.id.name`, where `val.node` is a ClassDeclaration with a null id.

**Comment by ljharb** [comment]
While it's a very bad practice for debuggability to have an unnamed component, we certainly shouldn't crash on it.

**Comment by ljharb** [comment]
Which rule is this crashing on?

**Comment by wereHamster** [comment]
Not sure, I think I had all the recommended rules enabled (and only disabled a few which I don't need).

**Comment by ljharb** [comment]
Could you provide the full stack trace?

**Comment by wereHamster** [comment]
```
TypeError: Cannot read property 'name' of null
Occurred while linting …/src/pages/[locale]/countries.tsx:260
    at …/node_modules/eslint-plugin-react/lib/util/Components.js:580:28
    at Array.map (<anonymous>)
    at Object.getDetectedComponents (…/node_modules/eslint-plugin-react/lib/util/Components.js:578:10)
    at Object.nodeWrapsComponent (…/node_modules/eslint-plugin-react/lib/util/Components.js:592:34)
    at Object.isPragmaComponentWrapper (…/node_modules/eslint-plugin-react/lib/util/Components.js:605:20)
    at Object.CallExpression (…/node_modules/eslint-plugin-react/lib/util/Components.js:849:18)
    at updatedRuleInstructions.<computed> (…/node_modules/eslint-plugin-react/lib/util/Components.js:974:43)
    at …/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (…/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

**Comment by wereHamster** [comment]
The whole file is something like

```jsx
export default class extends React.PureComponent {
  render() {
    return <Card />;
  }
}

const Card = (() => {
  return React.memo(({ }) => (
    <div />
  ));
})();
```

**Comment by ljharb** [comment]
hmm, ok thanks :-) i'll try to make a repro case.
