### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by avi-dwave** [yannickcr/eslint-plugin-react#2861]
### Environment Info:
- Node version: v10.23.0
- npm version: v6.14.8
- Local ESLint version: v7.13.0
- Global ESLint version: v7.13.0 (Currently used)

### Command Run
```bash
eslint ./assets/js/shared/component/partial/ProfileFlyoutV2/ProfileFlyoutV2.jsx
```

### Output
```bash
Oops! Something went wrong! :(

ESLint: 7.13.0

RangeError: Maximum call stack size exceeded
Occurred while linting /home/developer/work/sapi/qubist/metalab-cloud-service/assets/js/shared/component/partial/ProfileFlyoutV2/ProfileFlyoutV2.jsx:97
    at Array.join (native)
    at iterateProperties (/home/developer/work/sapi/qubist/metalab-cloud-service/node_modules/eslint-plugin-react/lib/util/propTypes.js:445:55)
    at iterateProperties (/home/developer/work/sapi/qubist/metalab-cloud-service/node_modules/eslint-plugin-react/lib/util/propTypes.js:65:7)
    at buildReactDeclarationTypes (/home/developer/work/sapi/qubist/metalab-cloud-service/node_modules/eslint-plugin-react/lib/util/propTypes.js:443:11)
    at buildReactDeclarationTypes (/home/developer/work/sapi/qubist/metalab-cloud-service/node_modules/eslint-plugin-react/lib/util/propTypes.js:458:25)
    at iterateProperties (/home/developer/work/sapi/qubist/metalab-cloud-service/node_modules/eslint-plugin-react/lib/util/propTypes.js:446:29)
    at iterateProperties (/home/developer/work/sapi/qubist/metalab-cloud-service/node_modules/eslint-plugin-react/lib/util/propTypes.js:65:7)
    at buildReactDeclarationTypes (/home/developer/work/sapi/qubist/metalab-cloud-service/node_modules/eslint-plugin-react/lib/util/propTypes.js:443:11)
    at buildReactDeclarationTypes (/home/developer/work/sapi/qubist/metalab-cloud-service/node_modules/eslint-plugin-react/lib/util/propTypes.js:458:25)
    at iterateProperties (/home/developer/work/sapi/qubist/metalab-cloud-service/node_modules/eslint-plugin-react/lib/util/propTypes.js:446:29)
```

### ProfileFlyoutV2.jsx lines 88-103
```js
const projectType = PropTypes.shape({
  id: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
});

const nodesType = PropTypes.arrayOf(
  PropTypes.shape({ project: projectType, children: nodesType }),
);

ProjectNode.propTypes = { // line 97 where the error occurs
  project: projectType.isRequired,
  nodes: nodesType,
  depth: PropTypes.number.isRequired,
  setActiveProject: PropTypes.func.isRequired,
  activeProject: projectType,
};
```

**Comment by avi-dwave** [comment]
Oh, I think I know why - nodesType is recursive. Is there a way to allow this type of structure?

**Comment by ljharb** [comment]
Certainly the linter shouldn't crash on that.

However, I'm pretty sure recursive propTypes like that don't actually work in production - because `nodesType` is an error until it's finished being assigned, so I think your code is just wrong.
