### ISSUE TITLE
TypeError: Cannot read property 'local' of undefined

### ISSUE THREAD

**Issue by glasserc** [yannickcr/eslint-plugin-react#2899]
I'm trying to move from tslint to eslint for a project at work which is mixed TypeScript/JavaScript. While trying to migrate, I hit this error:

```
Occurred while linting /home/ethan/Jobs/Teachable/eslint-test-local-undefined/index.ts:1
    at ImportDeclaration (/home/ethan/Jobs/Teachable/eslint-test-local-undefined/node_modules/eslint-plugin-react/lib/rules/no-typos.js:180:53)
    at /home/ethan/Jobs/Teachable/eslint-test-local-undefined/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/ethan/Jobs/Teachable/eslint-test-local-undefined/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/ethan/Jobs/Teachable/eslint-test-local-undefined/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/home/ethan/Jobs/Teachable/eslint-test-local-undefined/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/home/ethan/Jobs/Teachable/eslint-test-local-undefined/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/home/ethan/Jobs/Teachable/eslint-test-local-undefined/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/ethan/Jobs/Teachable/eslint-test-local-undefined/node_modules/eslint/lib/linter/linter.js:952:32
    at Array.forEach (<anonymous>)
```

SSCCE: https://github.com/glasserc/eslint-test-local-undefined

**Comment by ljharb** [comment]
Thanks, the repro was very helpful.
