### ISSUE TITLE
Error while loading rule 'react/prefer-stateless-function': Cannot read property 'version' of null Occurred while linting

### ISSUE THREAD

**Issue by tipleavalentin** [yannickcr/eslint-plugin-react#3219]
Hi! 

I found a bug, please take a look, thanks! 

npx eslint src_site/pages/HomePage.js

Oops! Something went wrong! :(

ESLint: 8.8.0

TypeError: Error while loading rule 'react/prefer-stateless-function': Cannot read properties of null (reading 'version')
Occurred while linting D:\project\src_site\pages\HomePage.js
at getReactVersionFromContext (D:\project\node_modules\eslint-plugin-react\lib\util\version.js:92:81)
at testReactVersion (D:\project\node_modules\eslint-plugin-react\lib\util\version.js:138:28)
at usedPropTypesInstructions (D:\project\node_modules\eslint-plugin-react\lib\util\usedPropTypes.js:285:36)
at Function.componentRule (D:\project\node_modules\eslint-plugin-react\lib\util\Components.js:1018:37)
at createRuleListeners (D:\project\node_modules\eslint\lib\linter\linter.js:915:21)
at D:\project\node_modules\eslint\lib\linter\linter.js:1097:31
at Array.forEach ()
at runRules (D:\project\node_modules\eslint\lib\linter\linter.js:1034:34)
at Linter._verifyWithoutProcessors (D:\project\node_modules\eslint\lib\linter\linter.js:1382:31)
at Linter._verifyWithConfigArray (D:\project\node_modules\eslint\lib\linter\linter.js:1722:21)

![image](https://user-images.githubusercontent.com/14072036/155745450-a7aeccfd-34f5-4374-9da3-b558aa52b53f.png)

**Comment by tipleavalentin** [comment]
In .eslintrc I have:
"settings": {
    "react": {
      "version": "latest"
    }
  }

With version: "17.0.2" it doesn't throw this error.

**Comment by ljharb** [comment]
Thanks, fix incoming.

**Comment by ljharb** [comment]
Actually, the issue is that "latest" is an invalid value. It supports a semver version range, or "detect". "latest" is not a semver range, it's just an npm tag.

I'll try to improve the error message here.

**Comment by ljharb** [comment]
v7.29.1 is released.
