### ISSUE TITLE
Components.js throws on component

### ISSUE THREAD

**Issue by tmcw** [yannickcr/eslint-plugin-react#364]
```
/home/ubuntu/studio/node_modules/eslint-plugin-react/lib/util/Components.js:296
        if (!node.properties) {
                 ^

TypeError: Cannot read property 'properties' of undefined
    at Object.utils.getRelatedComponent (/home/ubuntu/studio/node_modules/eslint-plugin-react/lib/util/Components.js:296:18)
    at EventEmitter.MemberExpression (/home/ubuntu/studio/node_modules/eslint-plugin-react/lib/rules/display-name.js:134:29)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/home/ubuntu/studio/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/home/ubuntu/studio/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/home/ubuntu/studio/node_modules/eslint/lib/eslint.js:767:36)
    at Controller.__execute (/home/ubuntu/studio/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/ubuntu/studio/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/home/ubuntu/studio/node_modules/eslint/lib/eslint.js:764:24)
```

Unfortunately I can't associate this with a specific input yet because it's only occurring on a CI server, but this is using eslint-plugin-react 3.11.3 and babel-eslint 5.0.0-beta6.

**Comment by tmcw** [comment]
This was caused by something like:

```js
        <div className={`strong fill-lighten0 pad1 contain small icon ${typeLabel[type].icon}`}>
          {typeLabel[type].displayName}
       </div>
```

Pretty sure having an object with a `displayName` property is confusing eslint-plugin-react.

**Comment by yannickcr** [comment]
I was not able to reproduce the crash, but I added an additional check that should prevent this case. 

Don't hesitate to reopen this issue if your problem is not resolved.
