### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined @ Object.utils.getRelatedComponent

### ISSUE THREAD

**Issue by hfwang** [yannickcr/eslint-plugin-react#383]
I'm getting this when I run eslint:

```
/path_to_code/node_modules/eslint-plugin-react/lib/util/Components.js:298
        if (!node.properties) {
                 ^

TypeError: Cannot read property 'properties' of undefined
    at Object.utils.getRelatedComponent (/path_to_code/node_modules/eslint-plugin-react/lib/util/Components.js:298:18)
    at EventEmitter.MemberExpression (/path_to_code/node_modules/eslint-plugin-react/lib/rules/prop-types.js:608:33)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/path_to_code/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/path_to_code/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/path_to_code/node_modules/eslint/lib/eslint.js:767:36)
    at Controller.__execute (/path_to_code/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/path_to_code/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/path_to_code/node_modules/eslint/lib/eslint.js:764:24)
```

Things seem reasonable if I change that line to instead be `if (!node || !node.properties) {` but that's a pretty dirty hack.

**Comment by hfwang** [comment]
I get this error even with the following JSX file:

```
class ComponentName extends React.Component {
}
ComponentName.propTypes = {};
```
