### ISSUE TITLE
3.16.0 broke the jsx-sort-prop-types rule

### ISSUE THREAD

**Issue by globexdesigns** [yannickcr/eslint-plugin-react#408]
After upgrading from 3.15.0 to 3.16.0 I am unable to run ESLint due to this error:

```
R:\Work\Github\afk-app\node_modules\eslint-plugin-react\lib\rules\jsx-sort-prop-types.js:43
    return node.value.property.name;

TypeError: Cannot read property 'name' of undefined
    at getValueName (R:\Work\Github\afk-app\node_modules\eslint-plugin-react\lib\rules\jsx-sort-prop-types.js:43:31)
    at isRequiredProp (R:\Work\Github\afk-app\node_modules\eslint-plugin-react\lib\rules\jsx-sort-prop-types.js:51:12)
    at R:\Work\Github\afk-app\node_modules\eslint-plugin-react\lib\rules\jsx-sort-prop-types.js:64:31
    at Array.reduce (native)
    at checkSorted (R:\Work\Github\afk-app\node_modules\eslint-plugin-react\lib\rules\jsx-sort-prop-types.js:60:18)
    at EventEmitter.ClassProperty (R:\Work\Github\afk-app\node_modules\eslint-plugin-react\lib\rules\jsx-sort-prop-types.js:109:9)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (R:\Work\Github\afk-app\node_modules\eslint\lib\util\node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (R:\Work\Github\afk-app\node_modules\eslint\lib\util\comment-event-generator.js:98:23)
```

Any ideas?

**Comment by yannickcr** [comment]
Can you past the source code that trigger this error ?

**Comment by NullDivision** [comment]
Same here. Same issue. Only applicable to propType declarations for `shape`. Everything else works.

**Comment by alitaheri** [comment]
I'm trying to add a failing test. and possibly fix it :grin:

**Comment by alitaheri** [comment]
The problem is with the custom propTypes. I'm fixing it now

**Comment by NullDivision** [comment]
I'm not sure it's just that. I get the issue with something like:

```
Application.propTypes = {
  actions: React.PropTypes.shape({
    displayError: React.PropTypes.func
  })
};
```

**Comment by alitaheri** [comment]
Well what I did also fixes this. but I'm not sure if it will behave correctly...

Anyway, I'll just make the PR so we can continue the discussion there :grin:

**Comment by yannickcr** [comment]
Fixed in `v3.16.1`, sorry for this (and thanks to @alitaheri for the fix!)

**Comment by alitaheri** [comment]
Anytime :grin:

**Comment by globexdesigns** [comment]
Confirmed. All good now :) Thanks for the quick fix guys.

**Comment by NullDivision** [comment]
Awesome. Issue fixed. Thank you @alitaheri :+1:

**Comment by alitaheri** [comment]
Glad I could help ^_^
