### ISSUE TITLE
the rule "react/jsx-quotes" is deprecated, please revise it to "jsx-quotes"

### ISSUE THREAD

**Issue by playtocrazy** [yannickcr/eslint-plugin-react#416]
`react/jsx-quotes` was deprecated for some time, please revise it to `jsx-quotes`, thank you.
reference: [https://github.com/airbnb/javascript/issues/513](url)

**Comment by yannickcr** [comment]
Sorry, I don't understand your point. `react/jsx-quotes` rule was deprecated in `v3.4.0` and will be removed in next major release.

**Comment by playtocrazy** [comment]
my editor is Atom and when I use the rule `react/jsx-quotes`, I got error message form Atom as following:

> Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:663:20)
    at SyncWriteStream.write (fs.js:1981:6)
    at Console.log (console.js:36:16)
    at EventEmitter.Program (C:\Users\richard.lin\AppData\Roaming\npm\node_modules\eslint-plugin-react\lib\rules\jsx-quotes.js:52:15)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (C:\Users\richard.lin\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (C:\Users\richard.lin\AppData\Roaming\npm\node_modules\eslint\lib\util\comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (C:\Users\richard.lin\AppData\Roaming\npm\node_modules\eslint\lib\eslint.js:767:36)

then I try to use `jsx-quotes`, it works fine now.
I just want to provide this information for everyone who get the same problem.

**Comment by sompylasar** [comment]
@playtocrazy if you're still interested in a solution, please vote for the issue about the cause of the error here: https://github.com/yannickcr/eslint-plugin-react/issues/783
