### ISSUE TITLE
Can't add property react, object is not extensible 

### ISSUE THREAD

**Issue by Niler851** [yannickcr/eslint-plugin-react#434]
```
/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/eslint.js:765
                    throw ex;
                    ^

TypeError: Error while loading rule 'react-native/no-unused-styles': Can't add property react, object is not extensible
    at Function.componentRule (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint-plugin-react-native/lib/util/Components.js:110:17)
    at /home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/eslint.js:754:25
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/eslint.js:729:16)
    at processText (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/cli-engine.js:602:23)
    at /home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/cli-engine.js:629:17
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/home/nils/Programmering/ahead/mobile_app/node_modules/eslint/lib/cli-engine.js:624:18)
```
eslintrc.json http://pastebin.com/wpbARaB5

relevant package.json
```
{
  "devDependencies": {
    "eslint": "^2.0.0-rc.0",
    "eslint-config-airbnb": "^5.0.0",
    "eslint-plugin-react": "^3.16.1",
    "eslint-plugin-react-native": "^0.5.0"
  }
}
```
Maby of help https://github.com/yannickcr/eslint-plugin-react/pull/324

**Comment by yannickcr** [comment]
Yep, same problem as #324, but you are on the wrong project ;)

The problem come from `eslint-plugin-react-native` https://github.com/Intellicode/eslint-plugin-react-native.

**Comment by Niler851** [comment]
Lol sorry I was a bit to quick :p
