### ISSUE TITLE
no-did-mount-set-state config is invalid

### ISSUE THREAD

**Issue by vkbansal** [yannickcr/eslint-plugin-react#444]
Getting the following error with eslint@2.0.0 and eslint-plugin-react@4.0.0-rc.0
```
Configuration for rule "react/no-did-mount-set-state" is invalid: Value "allowed-in-func" must be an enum value.
```

Rule used:
```
"react/no-did-mount-set-state": [1, "allowed-in-func"],
```

Extra info:
OS: WIndows 10
Editor: Atom 1.5.3
Atom Linter: 1.11.3
Atom Linter ESlint: 6.0.0

Stack Trace
```
Error: vkbansal/react:
	Configuration for rule "react/no-did-mount-set-state" is invalid:
	Value "allowed-in-func" must be an enum value.
Referenced from: E:\projects\andromeda\.eslintrc.yml
    at validateRuleOptions (E:\projects\andromeda\node_modules\eslint\lib\config\config-validator.js:111:15)
    at E:\projects\andromeda\node_modules\eslint\lib\config\config-validator.js:157:13
    at Array.forEach (native)
    at Object.validate (E:\projects\andromeda\node_modules\eslint\lib\config\config-validator.js:156:35)
    at load (E:\projects\andromeda\node_modules\eslint\lib\config\config-file.js:452:19)
    at E:\projects\andromeda\node_modules\eslint\lib\config\config-file.js:353:36
    at Array.reduceRight (native)
    at applyExtends (E:\projects\andromeda\node_modules\eslint\lib\config\config-file.js:336:28)
    at Object.load (E:\projects\andromeda\node_modules\eslint\lib\config\config-file.js:457:22)
    at loadConfig (E:\projects\andromeda\node_modules\eslint\lib\config.js:67:33)
```

**Comment by yannickcr** [comment]
The option is `allow-in-func`, not `allowed-in-func`.
