### ISSUE TITLE
Rule definitions not found (probably user error)

### ISSUE THREAD

**Issue by dmnd** [yannickcr/eslint-plugin-react#52]
I'm guessing this is user error, but can someone tell me why this doesn't work?

```
$ grep version node_modules/eslint-plugin-react/package.json 
  "version": "2.0.2",


$ grep version node_modules/eslint/package.json 
  "version": "0.18.0",


$ cat config.json 
{
  "rules": {
    "react/jsx-no-undf": 1
  },
  "plugins": [
    "react"
  ],
  "ecmaFeatures": {
    "jsx": true
  }
}


$ cat test.jsx 
console.log("foo");


$ ./node_modules/.bin/eslint -c config.json test.jsx 

/Users/dmnd/github/kultur/node_modules/eslint/lib/eslint.js:657
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'react/jsx-no-undf' was not found.
    at /Users/dmnd/github/kultur/node_modules/eslint/lib/eslint.js:657:27
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/dmnd/github/kultur/node_modules/eslint/lib/eslint.js:630:16)
    at processFile (/Users/dmnd/github/kultur/node_modules/eslint/lib/cli-engine.js:193:27)
    at /Users/dmnd/github/kultur/node_modules/eslint/lib/cli-engine.js:293:26
    at walk (/Users/dmnd/github/kultur/node_modules/eslint/lib/util/traverse.js:81:9)
    at /Users/dmnd/github/kultur/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/Users/dmnd/github/kultur/node_modules/eslint/lib/util/traverse.js:101:11)
    at CLIEngine.executeOnFiles (/Users/dmnd/github/kultur/node_modules/eslint/lib/cli-engine.js:284:9)
```

**Comment by yannickcr** [comment]
Hi,

There is a typo in the rule name in your configuration and ESLint cannot find this unknown rule.

The rule name should be `react/jsx-no-undef`:

```json
{
  "rules": {
    "react/jsx-no-undef": 1
  },
  "plugins": [
    "react"
  ],
  "ecmaFeatures": {
    "jsx": true
  }
}
```

**Comment by dmnd** [comment]
Thanks for pointing that out :blush: 

I copypasted those rules names but must have done something crazy in my editor without noticing.

**Comment by AntouanK** [comment]
I get the same error, and I'm pretty sure I got the name right :)

for example:
.eslintrc
```
{
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "ecmaFeatures": {
    "templateStrings": true,
    "arrowFunctions": true,
    "blockBindings": true,
    "modules": true,
    "forOf": true,
    "jsx": true
  },
  "plugins": [
    "react"
  ],
  "globals": {

  },
  "rules": {
     "react/jsx-no-duplicate-props": 1
   }
}
```

output ( I print errors inside a gulp task )
```
[gulp] /client/src/scripts/ROOT_STATE.js ln 2, col 1  warning Definition for rule 'react/jsx-no-duplicate-props' was not found
```
same messsage for all the files.

I use eslint like this ( although it should be irrelevant ):
```
const eslint        = require('eslint');

//    get a linter reference
const linter        = eslint.linter;

// read .eslintrc
const eslintrc      = JSON.parse(
  fs.readFileSync( path.resolve(__dirname, '.eslintrc') ).toString()
);

//  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  lint-scripts
gulp.task('lint-scripts', () => {

  return gulp.src([
    `${paths.scripts}/**/*.js`,
    `${paths.scripts}/**/*.jsx`
  ])
  .pipe(
    tap(file => {

      let fileContents = file.contents.toString();
      let messages = linter.verify(fileContents, eslintrc);

      if(messages.length > 0){
        messages
        .map(msg => {
          msg.filePath = file.path;
          return msg;
        })
        .forEach(lintLogger);
      }
    })
  );
});
```
