### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by d7h** [yannickcr/eslint-plugin-react#579]
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at /path/to/src/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:59:14
    at Array.forEach (native)
    at checkForbidden (/path/to/src/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:55:18)
    at EventEmitter.ClassProperty (/path/to/src/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:89:9)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/path/to/src/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/path/to/src/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:609:23)
    at CommentEventGenerator.enterNode (/path/to/src/node_modules/eslint/lib/util/comment-event-generator.js:99:23)
    at Controller.traverser.traverse.enter /path/to/src/node_modules/eslint/lib/eslint.js:887:36)

This happens if I import props from another file and then define another prop in a Component. Like this:

```
import React from 'react';

import propTypes from './test.propTypes';

class Test extends react.component {

    static propTypes = {
        intl: React.propTypes.number,
        ...propTypes
    };
}
```

eslint version 2.8.0

**Comment by christianharke** [comment]
Dies liegt am Destructuring der propTypes und ist in folgendem Branch bereits gelöst:
https://github.com/infektweb/guidelines.v4/tree/fix-forbid-prop-types-linting-errors

Die Lösung ist einfach, das `intl` propType in die ausgelagerten propTypes umzuziehen und dann diese als einfache Variable zuzuweisen.
