### ISSUE TITLE
TypeError in require-render-return

### ISSUE THREAD

**Issue by jkrems** [yannickcr/eslint-plugin-react#589]
I think the latest update broke arrow function support in `require-render-return`:

```
TypeError: Cannot read property 'name' of undefined
    at getPropertyName (node_modules/eslint-plugin-react/lib/rules/require-render-return.js:57:20)
    at Object.ArrowFunctionExpression (node_modules/eslint-plugin-react/lib/rules/require-render-return.js:96:40)
```

Example:

```jsx
const DefaultSpinner = () => <Text>Spinner</Text>;
module.exports = DefaultSpinner;
```

**Comment by ljharb** [comment]
https://github.com/yannickcr/eslint-plugin-react/issues/564#issuecomment-218013994

**Comment by jkrems** [comment]
Ah, sorry. Should've searched harder.

**Comment by yannickcr** [comment]
No problem, you were both very fast to find the problem :)
