### ISSUE TITLE
ESLint check fails after upgrading to 5.2.0 - 'Cannot read property 'name' of undefined'

### ISSUE THREAD

**Issue by dorsha** [yannickcr/eslint-plugin-react#641]
Getting the following error after upgrading from 5.1.1 to 5.2.0:

![image](https://cloud.githubusercontent.com/assets/5429033/16148927/9e20d136-3495-11e6-8cc7-530dfa010eed.png)

This is a bit a blocker since our build fails.

Any idea?

**Comment by yannickcr** [comment]
Can you post the source code that trigger the crash? I will try to quickly push a bugfix release.

**Comment by dorsha** [comment]
Of course.

https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-no-bind.js#L23

Seems that callee.property is undefined.

This is the stacktrace:

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at EventEmitter.CallExpression (/Users/dorsha/dev/demisto/web-client/node_modules/eslint-plugin-react/lib/rules/jsx-no-bind.js:23:24)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/dorsha/dev/demisto/web-client/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/dorsha/dev/demisto/web-client/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/dorsha/dev/demisto/web-client/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/dorsha/dev/demisto/web-client/node_modules/eslint/lib/eslint.js:905:36)
    at Controller.__execute (/Users/dorsha/dev/demisto/web-client/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/dorsha/dev/demisto/web-client/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/dorsha/dev/demisto/web-client/node_modules/eslint/lib/util/traverser.js:36:33)
```

**Comment by yannickcr** [comment]
> I also tried on a single file and got the same error.

Well if you could isolate the piece of code in this file that trigger this error it will be very helpful for me to write a proper test case and a proper fix.

Thanks for your help :smiley:

**Comment by aviadl** [comment]
Here you are 
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';


class ErrorExample extends Component {

  render() {
    return <span></span>;
  }
}

export default connect()(ErrorExample);

**Comment by dorsha** [comment]
No Error:
```
import React, { Component } from 'react';
import { connect } from 'react-redux';

class ErrorExample extends Component {

  render() {
    return <div></div>;
  }
}

export default ErrorExample;

```

Error:
```
import React, { Component } from 'react';
import { connect } from 'react-redux';

class ErrorExample extends Component {

  render() {
    return <div></div>;
  }
}

export default connect()(ErrorExample);

```

This cause an error as well:
```
import React, { Component } from 'react';
import { injectIntl } from 'react-intl';

class ErrorExample extends Component {

  render() {
    return <div></div>;
  }
}

export default injectIntl(ErrorExample);

```

**Comment by dorsha** [comment]
Redux actions error:

```
import * as Api from '../util/api';

function updateTest(res) {
  return {
    type: 'TEST_TYPE',
    payload: res
  };
}

export function test() {
  return dispatch => {
    Api.post('/test', {})
      .then((res) => {
        dispatch(updateTest(res));
      });
  };
}

```

When removing the `dispatch(updateTest(res));` line there is no error...

**Comment by dorsha** [comment]
Our ESLint dependencies:
![image](https://cloud.githubusercontent.com/assets/5429033/16157926/632b489e-34c3-11e6-8519-2ff545a28ce9.png)

**Comment by Odywan55** [comment]
Any fixes?

**Comment by Odywan55** [comment]
Thanks a lot !

**Comment by yannickcr** [comment]
Thanks for your help, it should now be fixed in `v5.2.2`

**Comment by dorsha** [comment]
Yup, fixed.
Thanks for the quick response.

**Comment by Odywan55** [comment]
Thanks, it's working.

**Comment by Odywan55** [comment]
Can you advice me best elsling config for react-redux app, thanks

**Comment by Lisss13** [comment]
again:
`
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at propTypes.types.some.annotation (/Users/arseniymironov/WebstormProjects/work/app/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:792:49)
    at Array.some (native)
    at declarePropTypesForIntersectionTypeAnnotation (/Users/arseniymironov/WebstormProjects/work/app/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:783:30)
    at markPropTypesAsDeclared (/Users/arseniymironov/WebstormProjects/work/app/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:862:35)
    at markAnnotatedFunctionArgumentsAsDeclared (/Users/arseniymironov/WebstormProjects/work/app/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:957:7)
    at Object.handleFunctionLikeExpressions (/Users/arseniymironov/WebstormProjects/work/app/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:975:7)
    at updatedRuleInstructions.(anonymous function) (/Users/arseniymironov/WebstormProjects/work/app/node_modules/eslint-plugin-react/lib/util/Components.js:698:75)
    at listeners.(anonymous function).forEach.listener (/Users/arseniymironov/WebstormProjects/work/app/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/Users/arseniymironov/WebstormProjects/work/app/node_modules/eslint/lib/util/safe-emitter.js:47:38)
error An unexpected error occurred: "Command failed.
`
code: 
`
// @flow
import * as React from 'react'
import * as R from 'ramda'
import SelectLib from 'react-select'
import './select.scss'
import './blackSelect.scss'

const Select = (props: * & {black?: boolean}): React.Node => (
  <div className="black">
    <SelectLib {...props} />
  </div>
)

export default Select
`
