### ISSUE TITLE
ESLint regression build failing

### ISSUE THREAD

**Issue by ilyavolodin** [yannickcr/eslint-plugin-react#708]
ESLint core has a nightly regression build that runs unittests and lints a few popular projects with the latest master. For the last two days it's been failing on `eslint-plugin-react` unit tests. Not sure if it's a real problem or not.

```
  1) no-unused-vars invalid /*eslint jsx-uses-react:1*/ var React;:

      AssertionError: '\'React\' is defined but never used.' == '\'React\' is defined but never used'
      + expected - actual

      -'React' is defined but never used.
      +'React' is defined but never used
      
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:407:36)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:463:25)

  2) no-unused-vars invalid /*eslint jsx-uses-react:1*/ /** @jsx Foo */ var React; <div />;:

      AssertionError: '\'React\' is defined but never used.' == '\'React\' is defined but never used'
      + expected - actual

      -'React' is defined but never used.
      +'React' is defined but never used
      
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:407:36)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:463:25)

  3) no-unused-vars invalid /*eslint jsx-uses-react:1*/ var React; <div />;:

      AssertionError: '\'React\' is defined but never used.' == '\'React\' is defined but never used'
      + expected - actual

      -'React' is defined but never used.
      +'React' is defined but never used
      
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:407:36)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:463:25)

  4) no-unused-vars invalid /*eslint jsx-uses-vars:1*/ var App;:

      AssertionError: '\'App\' is defined but never used.' == '\'App\' is defined but never used'
      + expected - actual

      -'App' is defined but never used.
      +'App' is defined but never used
      
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:407:36)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:463:25)

  5) no-unused-vars invalid         /*eslint jsx-uses-vars:1*/        var App;        var unused;        React.render(<App unused=""/>);:

      AssertionError: '\'unused\' is defined but never used.' == '\'unused\' is defined but never used'
      + expected - actual

      -'unused' is defined but never used.
      +'unused' is defined but never used
      
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:407:36)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:463:25)

  6) no-unused-vars invalid         /*eslint jsx-uses-vars:1*/        class unused {}:

      AssertionError: '\'unused\' is defined but never used.' == '\'unused\' is defined but never used'
      + expected - actual

      -'unused' is defined but never used.
      +'unused' is defined but never used
      
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:407:36)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:463:25)

  7) no-unused-vars invalid         /*eslint jsx-uses-vars:1*/        class HelloMessage {          render() {            var HelloMessage = <div>Hello</div>;            return HelloMessage;          }        }:

      AssertionError: '\'HelloMessage\' is defined but never used.' == '\'HelloMessage\' is defined but never used'
      + expected - actual

      -'HelloMessage' is defined but never used.
      +'HelloMessage' is defined but never used
      
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:407:36)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:463:25)

  8) no-unused-vars invalid         /*eslint jsx-uses-vars:1*/        class HelloMessage {          render() {            var HelloMessage = <div>Hello</div>;            return HelloMessage;          }        }:

      AssertionError: '\'HelloMessage\' is defined but never used.' == '\'HelloMessage\' is defined but never used'
      + expected - actual

      -'HelloMessage' is defined but never used.
      +'HelloMessage' is defined but never used
      
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:407:36)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:463:25)
```

Let me know if you want/don't want me to post those issues in the future.

**Comment by ljharb** [comment]
Did eslint change to add or remove a trailing period on error messages?

**Comment by ilyavolodin** [comment]
Add: https://github.com/eslint/eslint/pull/6739

**Comment by ljharb** [comment]
@ilyavolodin Thanks - the regression build + issue post is awesome. Technically that change constitutes a breaking change, since our tests are now breaking.

However, `eslint-plugin-react` does not yet support `eslint` 3, and this is just tests. I'll try to update the test messages so they pass both with and without the periods - hopefully that will ensure there's no other failures.

**Comment by ljharb** [comment]
Actually, it kind of seems like `eslint`'s own RuleTester should maybe ignore trailing periods, since that's what we're using to validate this (or, accept a regex rather than a string)?

**Comment by yannickcr** [comment]
ESLint v3.2.0 was just published with this "breaking" change. I updated the dependencies and the tests to match with the new error message.

**Comment by ljharb** [comment]
Linking to https://github.com/yannickcr/eslint-plugin-react/commit/19ece14135897da6bf887ac3a818b0918b74da61
