### ISSUE TITLE
Error: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by dustinmoorenet** [yannickcr/eslint-plugin-react#784]
```
Error: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at hasRenderMethod (<project_src>/node_modules/eslint-plugin-react/lib/rules/require-render-return.js:79:62)
    at EventEmitter.Program:exit (<project_src>/node_modules/eslint-plugin-react/lib/rules/require-render-return.js:115:14)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.leaveNode (<project_src>/node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (<project_src>/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:628:23)
    at CommentEventGenerator.leaveNode (<project_src>/node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.leave (<project_src>/node_modules/eslint/lib/eslint.js:898:36)
    at Controller.__execute (<project_src>/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (<project_src>/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
```

Using Atom, I create a new react component and as I type `render` I receive the error above.
```javascript
import React, {Component, PropTypes} from 'react';

export default class Foo extends Component {
    render
}
```

**Comment by ljharb** [comment]
@dustinmoorenet I'm not sure why atom is linting mid-typing, but you have a syntax error right there, so you *should* be getting all kinds of errors in the linter. Try `render() {}` and see what happens?

**Comment by dustinmoorenet** [comment]
It is fine if I finish out my typing. There is no long pause either. As soon as I type the `r` in `render` is flashes the error.
