### ISSUE TITLE
prop-types crashes when using props as a spread attribute

### ISSUE THREAD

**Issue by lo1tuma** [yannickcr/eslint-plugin-react#8]
The following code causes the prop-types rule to crash:

```jsx
render: function () {
    return (
        <AnyElement {...this.props}>
             hello world
       </AnyElement>
    );
}
```

```
TypeError: Cannot read property 'name' of undefined
    at EventEmitter.MemberExpression (my-project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:39:46)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (my-project/node_modules/eslint/lib/eslint.js:683:25)
    at Controller.__execute (my-project/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (my-project/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify my-project/node_modules/eslint/lib/eslint.js:676:24)
    at processFile (my-project/node_modules/eslint/lib/cli-engine.js:172:23)
    at my-project/node_modules/eslint/lib/cli-engine.js:271:26
    at my-project/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
```

**Comment by lo1tuma** [comment]
Looking at the code, it would probably also crash with the following example:
```js
var props = this.props;
```
