### ISSUE TITLE
`no-children-prop` doesn't work with object rest/spread

### ISSUE THREAD

**Issue by ljharb** [yannickcr/eslint-plugin-react#872]
specifically `prop.key.name` doesn't work.

stack trace:
```sh
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at $PWD/node_modules/eslint-plugin-react/lib/rules/no-children-prop.js:58:26
    at Array.find (native)
    at EventEmitter.CallExpression ($PWD/node_modules/eslint-plugin-react/lib/rules/no-children-prop.js:57:34)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode ($PWD/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode ($PWD/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode ($PWD/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter ($PWD/node_modules/eslint/lib/eslint.js:898:36)
    at Controller.__execute ($PWD/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
```

Code:
```js
ReactDOM.render(
    React.createElement(Foo, {
      someProp: 'someValue',
      ...someObject,
    }),
    someDOMElement
  );
```

**Comment by ljharb** [comment]
Whoops, turns out this is a duplicate of #862.

@yannickcr this is a pretty sizable blocker for me, could we cut a release ASAP?

**Comment by dtothefp** [comment]
I'm experiencing this problem on `6.4.0`, is there something I'm missing? Saw https://github.com/yannickcr/eslint-plugin-react/pull/862 was merged

```js
function createComponent(ChildComponent, dataBindings) {
  const displayName = `ProvideContextComponent(${Component.displayName || Component.name})`;

  class ProvideContextComponent extends Component {
    static displayName = displayName;

    static contextTypes = dataBindings;

    render() {
      /**
       * Important to override context values with props because `formId` can be passed on the
       * `<Form />` as props or as context
       */
      return React.createElement(ChildComponent, {
        ...this.state,
        ...this.context,
        ...this.props
      });
    }
  }

  hoistNonReactStatics(ProvideContextComponent, Component);

  return ProvideContextComponent;
}
```

```
Module build failed: TypeError: Cannot read property 'name' of undefined
    at /Users/davidfox-powell/dev/build-boiler/node_modules/eslint-plugin-react/lib/rules/no-children-prop.js:57:26
```
