### ISSUE TITLE
TypeError: Cannot read config file: 

### ISSUE THREAD

**Issue by hozefaj** [yannickcr/eslint-plugin-react#994]
Atom is throwing the below error.

```
TypeError: Cannot read config file: 
/node_modules/eslint-plugin-react/index.js
Error: Cannot read property 'deprecated' of undefined
Referenced from: /.eslintrc
    at /node_modules/eslint-plugin-react/index.js:86:20
    at filterRules (/node_modules/eslint-plugin-react/index.js:67:38)
    at Object.<anonymous> (/node_modules/eslint-plugin-react/index.js:85:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

`devDependencies` within my `package.json` are below.

```
"eslint": "^3.11.1",
"eslint-loader": "^1.3.0",
"eslint-plugin-babel": "^4.0.0",
"eslint-plugin-promise": "^3.4.0",
"eslint-plugin-react": "^6.8.0",
```

Has anyone seen this error before and some help on how to resolve this?

**Comment by ljharb** [comment]
`eslint-loader` seems to not be compatible with eslint 3 - https://unpkg.com/eslint-loader@1.3.0/package.json. You'll want to upgrade that to the latest, which does https://unpkg.com/eslint-loader@1.6.1/package.json

**Comment by hozefaj** [comment]
I actually do have `"version": "1.6.1"` of `eslint-loader` installed. 

Anyways, restarting my system solved the problem. Not sure what might have caused it in the first place. Cause it was working fine last night. 

Thanks for help.
